### ISSUE TITLE
Replace JSON parser

### ISSUE THREAD

**Issue by enridaga** [SPARQL-Anything/sparql.anything#103]
The current JsonIter is a dead project, with security issues reported by https://github.com/SPARQL-Anything/sparql.anything/security/dependabot/pom.xml/com.jsoniter:jsoniter/open

**Comment by justin2004** [comment]
[json2rdf](https://github.com/AtomGraph/JSON2RDF) uses
javax.json.stream.JsonParser

**Comment by enridaga** [comment]
A stream parser example with Gson: https://howtodoinjava.com/gson/jsonreader-streaming-json-parser/

**Comment by enridaga** [comment]
This may help the discussion: https://github.com/fabienrenaud/java-json-benchmark

**Comment by enridaga** [comment]
`Jackson` seems a good balance between performance and stability. We don't want to get ourselves again in the situation of depending on a library that is not maintained appropriately.
