### ISSUE TITLE
Binding Java methods to SPARQL functions

### ISSUE THREAD

**Issue by enridaga** [SPARQL-Anything/sparql.anything#105]
We should allow an easier way to map Java objects' methods to SPARQL functions. This can be done using reflection for both static and non-static methods. There may be limitations, though, to be identified.

**Comment by justin2004** [comment]
I wonder if [this example](https://www.bobdc.com/blog/arqjavascript/) calling js functions using ARQ would be useful as a reference?

**Comment by enridaga** [comment]
Yes, that's a useful feature. In this case, I am more thinking of exposing a number of Java libraries such as `java.lang.Math` that provides a collection of methods on basic data types. We used this approach for implementing #101 #104 and it seems to work. Other useful methods would be the ones to manipulate dates and time, but I suspect they will require a bit more attention to implement conversions between data formats and SPARQL data types.

**Comment by Aklakan** [comment]
Hi again ;)

We created an annotation-based java-jena function binder for that purpose. It creates dynamic proxy implementations of jena functions that bind to the java functions. Again its not (yet) part of jena itself, but as I am seeing the demand for these features grow I'd gladly contribute that work :)

So far its part of the maven dependency
```bash
<dependency>
    <groupId>org.aksw.jena-sparql-api</groupId>
    <artifactId>jena-sparql-api-mapper-proxy</artifactId>
    <version>3.17.0-1</version>
</dependency>
```
The release for jena 4.2.0 is scheduled before Oct 15.



[JenaExtensionGeoSparql.java](https://github.com/SmartDataAnalytics/jena-sparql-api/blob/develop/jena-sparql-api-sparql-ext/src/main/java/org/aksw/jena_sparql_api/sparql/ext/geosparql/JenaExtensionsGeoSparqlX.java#L57)

```java
        FunctionBinder binder = JenaExtensionUtil.createFunctionBinder(FunctionRegistry.get());
        FunctionGenerator generator = binder.getFunctionGenerator();

        // Define two-way Geometry - GeometryWrapper coercions
        generator.getConverterRegistry()
            .register(Geometry.class, GeometryWrapper.class,
                    geometry -> new GeometryWrapper(geometry, WKTDatatype.URI),
                    GeometryWrapper::getParsingGeometry)
            ;

        // Declare that the conversion of Geometry to GeometryWrapper
        // yields an RDF-compatible java object w.r.t. Jena's TypeMapper
        binder.getFunctionGenerator().getJavaToRdfTypeMap().put(Geometry.class, GeometryWrapper.class);

        // Map GeometryWrapper to the IRI of the WKT datatype
        // WKTDatatype.getJavaClass() in Jena4 incorrectly returns null instead of GeometryWrapper.class
        generator.getTypeByClassOverrides().put(GeometryWrapper.class, WKTDatatype.URI);

        binder.registerAll(GeoFunctionsJena.class);
```

[GeoFunctionsJena.java](https://github.com/SmartDataAnalytics/jena-sparql-api/blob/develop/jena-sparql-api-sparql-ext/src/main/java/org/aksw/jena_sparql_api/sparql/ext/geosparql/GeoFunctionsJena.java#L11)
```java
public class GeoFunctionsJena {	
	@IriNs(GeoSPARQL_URI.GEOF_URI)
	public static Geometry simplifyDp(
			Geometry geom,
			@DefaultValue("0") double tolerance,
			@DefaultValue("true") boolean ensureValid) {
		DouglasPeuckerSimplifier simplifier = new DouglasPeuckerSimplifier(geom);
		simplifier.setDistanceTolerance(tolerance);
		simplifier.setEnsureValid(ensureValid);
		Geometry result = simplifier.getResultGeometry();
		return result;
	}
}
```

This allows one to use the simplifyDp function in sparql - such as `SELECT (geof:simplifyDp("POLYGON((...))"^^geo:wktLiteral) AS ?simpleGeom) { }`
Default arguments can be omitted when invoking the sparql function.

**Comment by enridaga** [comment]
Very interesting, I would like to add GeoSpatial functions to SPARQL Anything!

**Comment by justin2004** [comment]
I haven't tried this but: https://jena.apache.org/documentation/geosparql/

**Comment by Aklakan** [comment]
We are using jena geosparql and you may also be interested in the extensions from https://github.com/i3mainz/jena-geo
But still there are cases where additional sparql function extensions are needed, and the annotation-based function binder makes this task easy :)

**Comment by enridaga** [comment]
OK, I like the discussion on this topic and will open specific issues on Geospatial features. However, the feature developed allows exposing existing Java libraries without the need to write additional code. This is solved, now.
