### ISSUE TITLE
Entity construction functions

### ISSUE THREAD

**Issue by enridaga** [SPARQL-Anything/sparql.anything#106]
A lot of work to concatenate strings and casting ... I am wondering whether any of the following syntaxes may make things easier:
```
BIND ( IRI( CONCAT("https://w3id.org/spice/imma/agent/", ?artistNickname ) ) as ?artistEntity ) . # standard
BIND ( fx:concat (tsub:, ?artistNickname )  as ?asString )  .  # implicit convert to STR
BIND ( fx:template("https://w3id.org/spice/imma/agent/${artistNickname}") as ?asString ) . # using a template engine to map to variables in scope	
BIND ( fx:entity("https://w3id.org/spice/imma/agent/${nickname}") as ?asIRI ) . # template engine + cast to IRI
BIND ( fx:entity( entityNS: , "-${artistNickname}") as ?asIRI ) . # all of the above?
```

**Comment by justin2004** [comment]
i usually do
```
BIND ( IRI( CONCAT(str(tsub:), ?artistNickname ) ) as ?artistEntity )
```

**Comment by enridaga** [comment]
>i usually do
>> BIND ( IRI( CONCAT(str(tsub:), ?artistNickname ) ) as ?artistEntity )

Yes, that's the most compact available at the moment. 

This one may be problematic:
```
BIND ( fx:template("https://w3id.org/spice/imma/agent/${artistNickname}") as ?asString ) . # using a template engine to map to variables in scope
```
since the query execution will need to test whether `?artistNickname` is evaluated before executing the function, and I am not sure this is possible without referencing an actual variable in scope.

Maybe a convenient function is one that can accept arguments of any length of any type, performs the appropriate `STR(?x)` castings, concatenate the strings, and builds the IRI, e.g.:
```
BIND ( fx:entity ( pref:, ?var2 ) AS ?myEntity) # simplest case
BIND ( fx:entity ( pref:, ?var, "/", ?var1, "#", ?var2 ) AS ?myEntity) # complex but common case
```
as shortcuts for:
```
BIND ( IRI ( CONCAT ( STR(pref:), ?var2 ) ) AS ?myEntity )
BIND ( IRI ( CONCAT ( STR(pref:), STR(?var), "/", STR(?var1), "#", ?var2 ) ) AS ?myEntity )
```
assuming `?var2` is string but the others aren't.
