### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by enridaga** [SPARQL-Anything/sparql.anything#108]
The README file is growing fast. Options:

- create a folder `/documentation` and move there the README file, then split it and reorganise it
- move it to the Wiki
- move it to the website at `https://sparql-anything.cc`
- other options?

**Comment by justin2004** [comment]
I personally like single document READMEs. They are easy to maintain and make grepping simple. When I look at documentation and they have a "single HTML page" and "multiple HTML pages" I always use the single page.

I think SPARQL Anything's README is quite good too.
The only thing I would like to see more of is examples... which I think could also live in the README just like they do in man pages.

**Comment by enridaga** [comment]
ehm ... yes the other option is leaving as it is :D

**Comment by enridaga** [comment]
Still want to have nicer documentation, I am trying to publish one with [readthedocs.io](https://readthedocs.org/), first thing is to copy the readme.md in a docs/ folder. Let's see how it goes.

**Comment by enridaga** [comment]
Not bad, considering the zero effort: https://sparql-anything.readthedocs.io/en/latest/

**Comment by enridaga** [comment]
Some thinking on how to improve/manage documentation can be developed from https://www.mkdocs.org

**Comment by enridaga** [comment]
Tables in 'details' don't seem to work: https://sparql-anything.readthedocs.io/en/v0.6-dev/

**Comment by enridaga** [comment]
I consider this one closed as we are tracking improvements to documentation in #201
