### ISSUE TITLE
 Arbitrary file write during archive extraction ("Zip Slip")

### ISSUE THREAD

**Issue by enridaga** [SPARQL-Anything/sparql.anything#111]
See https://github.com/SPARQL-Anything/sparql.anything/security/code-scanning/2?query=ref%3Arefs%2Fheads%2Fv0.3-DEV

**Comment by justin2004** [comment]
I get a 404 for that URL. (or maybe it was just a note for yourself)

**Comment by enridaga** [comment]
Yes, that's a security alert, can't be seen if not admin. Description is: "Extracting files from a malicious archive without validating that the destination file path is within the destination directory can cause files outside the destination directory to be overwritten."

**Comment by luigi-asprino** [comment]
Closed via 152602c70d1f54d63eb68f70ec5887b825882bdd implemented suggestions found [here](https://codeql.github.com/codeql-query-help/java/java-zipslip/)
