### ISSUE TITLE
CSV Delimiter support

### ISSUE THREAD

**Issue by Sarra-Ouelhadj** [SPARQL-Anything/sparql.anything#112]
It will be very useful to be able to set the delimiter of the csv file (e.g. ';' instead of ',').

**Comment by enridaga** [comment]
Indeed!

**Comment by enridaga** [comment]
There is a new option `csv.delimiter` which should do the job. Please try it out and let us know if the issue is resolved.

**Comment by Sarra-Ouelhadj** [comment]
> There is a new option `csv.delimiter` which should do the job. Please try it out and let us know if the issue is resolved.

I'm using the executable JAR for Fuseki in my tests. Would you mind making a new release for me to test? if there is another way to test, I would be glad to know it. Thank you in advance.

**Comment by enridaga** [comment]
You can clone the project and compile with Maven, as follows:
```
git clone https://github.com/SPARQL-Anything/sparql.anything
cd sparql.anything
man clean install
```
the runnable Fuseki is in `sparql.anything/sparql.anything.fuseki/target/`.

Otherwise, we plan to sketch a release candidate next week.

**Comment by justin2004** [comment]
@Sarra-Ouelhadj if you are using Fuseki [this](https://github.com/SPARQL-Anything/sparql.anything/blob/v0.3-DEV/BROWSER.md) is a quick way to run the latest commit.

**Comment by Sarra-Ouelhadj** [comment]
Thank you @justin2004 @enridaga , it works great!
