### ISSUE TITLE
Safe but pretty local names for keys

### ISSUE THREAD

**Issue by enridaga** [SPARQL-Anything/sparql.anything#113]
The system builds properties using a namespace (default `http://sparql.xyz/facade-x/data/`) and the local name derived from the data, for example, the CSV column or the JSON property.

However, not all the strings are valid IRIs. Currently, we leave to each triplifier to prepare the slot `key`, in FX terminology. 
For example, the JSON triplifier in v0.3.1 replace all non alphabetic characters to URL-encoded strings, for example `track_id` becoming `track%5Fid`. This may confuse users.

I think we should discuss a policy for preparing local names, and keeping them as much as possible as they are in the original source.
Possibly, implementing an operation on the abstract triplifier to make any string a pretty but safe local name.

**Comment by justin2004** [comment]
We were happy to see that SPARQL Anything handles things like spaces in keys.

JSON2RDF [doesn't](https://github.com/AtomGraph/JSON2RDF/issues/6).

We don't mind the url encoding but we do have to use <> around URIs when they've been url encoded (in a query). That is a super minor inconvenience though.

**Comment by enridaga** [comment]
> We don't mind the url encoding but we do have to use <> around URIs when they've been url encoded (in a query). That is a super minor inconvenience though.

Good point, the usability of local names in querying is important, as we want developers to easily use the strings as they look like in the original sources as much as possible

**Comment by justin2004** [comment]
> but we do have to use <> around URIs when they've been url encoded (in a query).

It seems I was wrong about that. I just tried to use a predicate like `xyz:classification%20one` in a query and it works fine. Also it is valid turtle to use that as well although Jena doesn't produce it.

**Comment by namedgraph** [comment]
JSON2RDF now supports spaces in keys ;)

**Comment by enridaga** [comment]
I am not sure why this is still open, I think this was handled in #246 and #248
