### ISSUE TITLE
Renamed fuseki server jar

### ISSUE THREAD

**Issue by enridaga** [SPARQL-Anything/sparql.anything#118]
When performing #40 we also renamed the executable produced by `sparql-anything-fuseki`. The new name is `sparql-anything-server-VERSION.jar`. References in documentation should be updated.

**Comment by enridaga** [comment]
Any other reference?

**Comment by justin2004** [comment]
yeah, in Dockerfile.development. i can make a PR for that one if you like.

**Comment by enridaga** [comment]
Should be solved
