### ISSUE TITLE
apache commons text functions

### ISSUE THREAD

**Issue by enridaga** [SPARQL-Anything/sparql.anything#121]
Nice utilities from commons-text:

- [WordUtils](https://commons.apache.org/proper/commons-text/javadocs/api-release/org/apache/commons/text/WordUtils.html)
- [CaseUtils](https://commons.apache.org/proper/commons-text/javadocs/api-release/org/apache/commons/text/CaseUtils.html)

**Comment by luigi-asprino** [comment]
I integrated functions from WordUtils and DigestUtils and we can maybe postpone the integration of CaseUtils after we address the issue #166
