### ISSUE TITLE
HTML profiles: DOM, Microdata, RDFa, ...

### ISSUE THREAD

**Issue by enridaga** [SPARQL-Anything/sparql.anything#13]
HTML can be a data source in many different ways. Currently, we support a CSS-selector and generate a Facade-X representation of the related DOM portions (each solution in a separate graph). We should consider also alternative approaches, for example, referring to well-known approaches to embed data, such as Microdata or RDFa.

**Comment by luigi-asprino** [comment]
I think we can close this, right?
