### ISSUE TITLE
feature request: support csv.null-string for all file types

### ISSUE THREAD

**Issue by justin2004** [SPARQL-Anything/sparql.anything#134]
We used the new spreadsheet triplifier (worked nicely!) but we missed the csv.null-string option.

low priority.

**Comment by justin2004** [comment]
Actually I don't think it would be as important for SPARQL Anything to implement features like csv.null-string if SPARQL supported nested constructs. Then we could just...

```
construct {?sub ?pred ?obj .
                 ?othersub rdfs:label ?label } 
                 where {
    # do your real work here
    construct {?s ?p ?o} where {
    filter(?o != "") 
    }
}
```

**Comment by enridaga** [comment]
It is useful to have a  `null-string` global option.

**Comment by enridaga** [comment]
Actually, the global `null-string` option has a different semantics and usage from the CSV one. The global one is a boolean flag: ignore triples where the object value is an empty string. While the `csv.null-string` option accepts any string that, when met as a value, makes the triple ignored. Shall we replicate the same behaviour?

**Comment by enridaga** [comment]
> Shall we replicate the same behaviour?

That was a rhetoric question :)

**Comment by justin2004** [comment]
We'll be using this feature right away! Thanks!
