### ISSUE TITLE
Location to point to a specific file in an archive

### ISSUE THREAD

**Issue by enridaga** [SPARQL-Anything/sparql.anything#140]
Currently, it is possible to explore the content of an archive. However, it could be useful to point to a specific entry within an archive. This comes in handy when you have large sets of files and you don't want to unpack the archive for reading it.

**Comment by luigi-asprino** [comment]
This can be done by combining two options: `from-archive` which specifies the URL of the archive and `location` which specifies the target file path within the archive.
This pattern is used in the [propbank showcase](https://github.com/SPARQL-Anything/showcase-propbank/blob/main/predicate2framester.sparql)
