### ISSUE TITLE
Release on Maven central

### ISSUE THREAD

**Issue by enridaga** [SPARQL-Anything/sparql.anything#153]
As the summary says.

**Comment by luigi-asprino** [comment]
We opened [an issue](https://issues.sonatype.org/browse/OSSRH-91794?page=com.atlassian.jira.plugin.system.issuetabpanels:all-tabpanel) for registering the groupId, however groupids com.github.* became invalid. Therefore the groupid of the project will become io.gitub.sparqlanything

**Comment by luigi-asprino** [comment]
[2375b46](https://github.com/SPARQL-Anything/sparql.anything/commit/2375b46b6daf2dea8301c41053b01994ed0c72a2) renames group id as io.github.sparqlanything.
However, considering the current organisation name the group id should be io.github.sparql-anything. 
I would like to have package names starting with the group id, but Java packages cannot have hyphens in their names. Therefore, I cannot see other solution than changing the organisation name to SPARQLAnything.
GitHub should manage the redirect properly, are there any other issues to consider?

**Comment by luigi-asprino** [comment]
By the way, this is a major change. I think this should be included in the upcoming 1.0.0 release

**Comment by enridaga** [comment]
> [2375b46](https://github.com/SPARQL-Anything/sparql.anything/commit/2375b46b6daf2dea8301c41053b01994ed0c72a2) renames group id as io.github.sparqlanything. However, considering the current organisation name the group id should be io.github.sparql-anything. I would like to have package names starting with the group id, but Java packages cannot have hyphens in their names. Therefore, I cannot see other solution than changing the organisation name to SPARQLAnything. GitHub should manage the redirect properly, are there any other issues to consider?

I remember you could have group ids with hyphes and java packages without and that was tolerated. Can you ask in the Maven/Jira ticket? Changing the organisation name is a big one, we have links everywhere now...

**Comment by enridaga** [comment]
> By the way, this is a major change. I think this should be included in the upcoming 1.0.0 release

No problem with that, we can skip version 9 like Windows...

**Comment by luigi-asprino** [comment]
> > [2375b46](https://github.com/SPARQL-Anything/sparql.anything/commit/2375b46b6daf2dea8301c41053b01994ed0c72a2) renames group id as io.github.sparqlanything. However, considering the current organisation name the group id should be io.github.sparql-anything. I would like to have package names starting with the group id, but Java packages cannot have hyphens in their names. Therefore, I cannot see other solution than changing the organisation name to SPARQLAnything. GitHub should manage the redirect properly, are there any other issues to consider?
> 
> I remember you could have group ids with hyphes and java packages without and that was tolerated. Can you ask in the Maven/Jira ticket? Changing the organisation name is a big one, we have links everywhere now...

I'm pretty sure it is tolerated. However, isn't that ugly?  (btw links will keep working as GH does the redirect)

**Comment by enridaga** [comment]
> > > [2375b46](https://github.com/SPARQL-Anything/sparql.anything/commit/2375b46b6daf2dea8301c41053b01994ed0c72a2) renames group id as io.github.sparqlanything. However, considering the current organisation name the group id should be io.github.sparql-anything. I would like to have package names starting with the group id, but Java packages cannot have hyphens in their names. Therefore, I cannot see other solution than changing the organisation name to SPARQLAnything. GitHub should manage the redirect properly, are there any other issues to consider?
> > 
> > 
> > I remember you could have group ids with hyphes and java packages without and that was tolerated. Can you ask in the Maven/Jira ticket? Changing the organisation name is a big one, we have links everywhere now...
> 
> I'm pretty sure it is tolerated. However, isn't that ugly? (btw links will keep working as GH does the redirect)

I would recommend minimising the changes (also, we discussed removing the dot from the repository name and never done it, so maybe that is one change to consider). Maybe we can just do the package name change now, and leave the rest as it is for now.

**Comment by luigi-asprino** [comment]
Well.. for now, will be probably forever  (unless we register a second group id in the future) :-)
I see two options here: 1) we change the organisation name now 2) we keep it as it is forever and we have with the group id ``io.github.sparql-anything`` and the package prefix ``io.github.sparqlanything``. 

EDIT: I'm ok with both solutions, although I would prefer the former.

**Comment by luigi-asprino** [comment]
[From GH](https://docs.github.com/en/organizations/managing-organization-settings/renaming-an-organization)

> After changing your organization's name, your old organization name becomes available for someone else to claim. When you change your organization's name, most references to your repositories under the old organization name automatically change to the new name. However, some links to your profile won't automatically redirect.


``name becomes available for someone else to claim.`` this is annoying

**Comment by luigi-asprino** [comment]
Maybe the second is safer from hijacking.

**Comment by luigi-asprino** [comment]
```
Congratulations! Welcome to the Central Repository!
io.github.sparql-anything has been prepared,
```

Once release 1.0.0 is ready, we release it on maven central.

**Comment by enridaga** [comment]
@luigi-asprino do you think we can try it with a v0.9.0-RC1 ?

**Comment by luigi-asprino** [comment]
Yes, as soon as the the RC1 is ready I can try to release it on maven

**Comment by enridaga** [comment]
We should consider implementing this as a CI workflow with GH actions: https://docs.github.com/en/actions/publishing-packages/publishing-java-packages-with-maven

**Comment by luigi-asprino** [comment]
The workflow finally works for snapshot releases. 
I mean, the snapshot is available on https://s01.oss.sonatype.org/content/repositories/snapshots/io/github/sparql-anything/

Let's see if we can make it also with staging releases.

**Comment by luigi-asprino** [comment]
I'm not sure if it is related to the workflow or to the fact that is a staging release, but using a revision name that doesn't end with "-SNAPSHOT" makes the deployment fail.
In the meanwhile, I receive messages from Sonatype saying that 68 threats are discovered in the artefacts I'm trying to push.

**Comment by enridaga** [comment]
> I'm not sure if it is related to the workflow or to the fact that is a staging release, but using a revision name that doesn't end with "-SNAPSHOT" makes the deployment fail. 

Maybe because that is a restriction of the snapshots repository? I think it is fair to consider -SNAPSHOT as the postfix of under-development version. We may target the main repository for releases (any of them, including non-official or pre-releases -DEV, -RC, ...)

**Comment by luigi-asprino** [comment]
In the meanwhile, I'm receiving messages from Sonatype saying that there are vulnerabilities in the dependencies. Maybe this prevents the artefacts from being released?

**Comment by luigi-asprino** [comment]
> Maybe because that is a restriction of the snapshots repository? I think it is fair to consider -SNAPSHOT as the postfix of under-development version. We may target the main repository for releases (any of them, including non-official or pre-releases -DEV, -RC, ...)

So is it just a matter of naming conventions?  In that case, I guess we will know when we release 0.9.1.

I just changed the trigger for the workflow. Was on the push event for testing it without the need of releasing something. Now it triggers on a new release.

**Comment by luigi-asprino** [comment]
We can finally close it as both 0.9.0 release candidate has been successfully deployed on Maven Central.

https://central.sonatype.com/search?namespace=io.github.sparql-anything
