### ISSUE TITLE
Implement blank-node=false for CSV, HTML, and XML

### ISSUE THREAD

**Issue by enridaga** [SPARQL-Anything/sparql.anything#18]
This should be straight-forward for all the currently supported formats.

**Comment by enridaga** [comment]
This is supported in JSON and Text. To be implemented in XML and HTML.

**Comment by luigi-asprino** [comment]
I think we can close this issue

**Comment by luigi-asprino** [comment]
Not sure how the HTML triplifier implements the blank-node=false option.
@enridaga, could you please check?

**Comment by luigi-asprino** [comment]
With 63c7c7d777c954134b00299d53202eb0ad04966f I've included a test for blank-nodes=false option for HTML.
The test fails.
