### ISSUE TITLE
feature request: (csv triplifier) option to ignore columns with no header value

### ISSUE THREAD

**Issue by justin2004** [SPARQL-Anything/sparql.anything#180]
sometimes people put marginal notes in spreadsheets that are not under any column header.
if we had an option like `fx:csv.ignore.columns.with.no.header "true"` then we wouldn't get errors..

OR

maybe it would be better to have an option like:
`fx:csv.generate.headers.if.missing "true"` to be paired with `fx:csv.headers "true"`

then there would be no errors and the query writer could just ignore the columns with the marginal notes.

(my colleague noticed this one too)

**Comment by luigi-asprino** [comment]
[aa44077](https://github.com/SPARQL-Anything/sparql.anything/commit/aa440771667f0312f65e6d2ebcbb01026013c7be) introduced `csv.ignore-columns-with-no-header` and `spreadsheet.ignore-columns-with-no-header`
