### ISSUE TITLE
experiments for streaming query execution (simple)

### ISSUE THREAD

**Issue by enridaga** [SPARQL-Anything/sparql.anything#189]
An execution strategy that streams the triples directly from the files during query execution.
This strategy triplifies the file multiple times, to answer a specific triple pattern, requested via a DatasetGraph interface.
The benefit of this approach is that it does not require loading the triples in memory before query execution (strategies 0 and 1).
The downside of this approach is that the file is read multiple times, for each one of the iterators needed to answer the query.

This was discussed previously in #135, see https://github.com/SPARQL-Anything/sparql.anything/issues/135#issuecomment-960585988

**Comment by enridaga** [comment]
4abd087b6eed5aa2bb35316a6240c9614884b116 provides an initial implementation, only supporting the CSV triplifier, for discussion and experiments.

**Comment by enridaga** [comment]
Something funny is going on when doing joins but can't figure out what it is yet.

For example, [this query from showcase-tate](https://github.com/SPARQL-Anything/showcase-tate/blob/main/queries/list-thumbnail-urls.sparql) does not work as expected, returning only 1 record when strategy = 2:
```
fx -q queries/list-thumbnail-urls.sparql -f CSV -s 2
```

**Comment by enridaga** [comment]
> Something funny is going on when doing joins but can't figure out what it is yet.

OK, the issue mentioned should be fixed in  1da3b0f272af49a66aa770ac0eca54b9b0da6ca0

**Comment by enridaga** [comment]
Now the strategy is working as intended. However, it is very inefficient as the file is parsed for every invocation of `DatasetGraph#find`.

Possible optimisation could involve any of the following approaches:

- Blocking strategies (on certain quad patterns, we may know when the solution is complete and stop parsing)
- Saving partial results (inspecting the BGP and second-guess subsequent invocations)
- Caching subsequent invocations of the same quad pattern
- Indexing of the file before execution (where are the containers? where is container X?)
- Others?

**Comment by enridaga** [comment]
I am progressing this stream of activity in the following way.

The file is parsed only at first invocation, then data is attached to the containers, incrementally. Subsequent calls to the `find(g,s,p,o)` functions are returning data stored in the container `s`. The idea is that the file is streamed only if the calling quad pattern does not provide a subject which is a container that was in turn generated by a previous call. This should reduce the number of times the file is parsed dramatically. If this works, we may think of other ways of remembering generated triples, instead of keeping them in memory. 

This is experimental, and it may or may not work :)

**Comment by enridaga** [comment]
The current implementation requires extending Jena `Node`, which is only possible for `Node_Uri` nodes (blank nodes cannot be extended at the moment, the constructor is not visible). I want first to be sure this is a viable solution before asking the Jena people to expose the constructor of Node_Blank.

**Comment by enridaga** [comment]
Please note that this is not working at the moment. Test failing: https://github.com/SPARQL-Anything/sparql.anything/blob/dbe44ffeb8e7a3a11e62eb11ce38ce43aad0583e/sparql-anything-it/src/test/java/com/github/sparqlanything/it/FileStreamTest.java#L70

**Comment by enridaga** [comment]
The basic way out for the moment is creating an in-memory index of Quads while returning the first set of Quads. Future work then will be looking into options to remember the generated triples (better type of in-memory index or file system)

**Comment by enridaga** [comment]
After some more experiments, I don't believe this is going to improve the performance of reading large files and executing the query in memory. 

I think the mistake is that we are trying to use the same DatasetGraph interface for executing queries on an in-memory index dynamically populated. Although we can manage the various indexes so that iterators can wait for more data to be loaded (until the file parsing is completed), this does not seem to pay off compared to just loading everything in a Jena in-memory graph. Clearly, the Jena code for the indexes is much more efficient than what I developed in this experiment but, unfortunately, it is transactional, meaning that we cannot extract iterators that wait for the index to be fully populated. Making this work efficiently seems a long way to go and I don't feel it is really worth it, as in the end we may just end-up with a minor performance improvement (no need to wait for the data to be loaded to start streaming it out...)

At this point, it may be worth leaving this and focusing on other things to improve usability with large files, for example, slicing the input file, as discussed elsewhere.

**Comment by enridaga** [comment]
I will leave this issue open for a while and then remove the code before closing.

**Comment by justin2004** [comment]
maybe we could use [StreamRDF](https://jena.apache.org/documentation/javadoc/arq/org/apache/jena/riot/system/StreamRDF.html?is-external=true)? 
```
The interface for the output of RDF, such as the RIOT parsers. 
The parser event model is that items are emitted for significant events. 
The events are start/finish, emitting triples/quads/tuples as necessary, prefixes and base directives. 
Tuples are generalized triples or quads. A triple language will call triple(), quad language quad() in preference.
```

that is how [csv2rdf does it](https://github.com/AtomGraph/CSV2RDF/blob/master/src/main/java/com/atomgraph/etl/csv/stream/CSVStreamRDFProcessor.java#L82). that is, it operates on 1 row at a time.

**Comment by enridaga** [comment]
> that is how csv2rdf does it. that is, it operates on 1 row at a time.

Yes, my plan is to implement something similar, what was called Slicing #21 
With this approach, the input data is segmented according to some format-specific criteria (CSV->row, JSON->if the main element is an Array we can iterate over it or require a JsonPath as selector; XML-> requiring an XPath expression, ...)

**Comment by enridaga** [comment]
Code removed from development branch, tagged las `issue189`

**Comment by enridaga** [comment]
However, we can use  StreamRDF for improving the way triplifiers pass the RDF data, instead of committing to a DatasetGraph...
