### ISSUE TITLE
Handling namespaces for properties and entities

### ISSUE THREAD

**Issue by enridaga** [SPARQL-Anything/sparql.anything#19]
At the moment, the namespace option parameter is used as default prefix fro both schema elements and named entities. This may create problems, for example, when joining two CSVs. Users should declare different namespaces to avoid clashes. An easier way may be to use the root entity (file name) as default prefix.

**Comment by luigi-asprino** [comment]
We could add four options:
- ``containers-namespace`` to control the namespace of the containers
- ``properties-namespace`` to control the namespace of the properties
- ``classes-namespace`` to control the namespace of the classes
- ``graphs-namespace`` to control the namespace of the named graphs

The current `namespace` will be used to change the default namespace so that, for example, one can set the `namespace` and overrule it only for the classes.

**Comment by enridaga** [comment]
> the namespace option parameter is used as default prefix fro both schema elements and named entities.

I know I wrote this but is it still valid? I thought we used `root` for naming containers. The root being the resource path by default and sub-containers reuse that by appending local names according to conventions established for each triplifier. For example, csv starts with a `root` using the file path and then appends '#rowN` for each row.

**Comment by enridaga** [comment]
In the sandbox project there is a folder `/formats` where one can test the current behaviour. 
For example, with:
```bash
fx -v file=1.csv -q triplify.sparql 
```
I obtained:
```turtle

@prefix fx:  <http://sparql.xyz/facade-x/ns/> .
@prefix xyz: <http://sparql.xyz/facade-x/data/> .

<file:/Users/ed4565/Development/sparql-anything/sandbox/formats/1.csv##row3>
        <http://www.w3.org/1999/02/22-rdf-syntax-ns#_1>
                "A2" ;
        <http://www.w3.org/1999/02/22-rdf-syntax-ns#_2>
                "B2" ;
        <http://www.w3.org/1999/02/22-rdf-syntax-ns#_3>
                "C2" ;
        <http://www.w3.org/1999/02/22-rdf-syntax-ns#_4>
                "D2" .

<file:/Users/ed4565/Development/sparql-anything/sandbox/formats/1.csv#>
        a       fx:root ;
        <http://www.w3.org/1999/02/22-rdf-syntax-ns#_1>
                <file:/Users/ed4565/Development/sparql-anything/sandbox/formats/1.csv##row1> ;
        <http://www.w3.org/1999/02/22-rdf-syntax-ns#_2>
                <file:/Users/ed4565/Development/sparql-anything/sandbox/formats/1.csv##row2> ;
        <http://www.w3.org/1999/02/22-rdf-syntax-ns#_3>
                <file:/Users/ed4565/Development/sparql-anything/sandbox/formats/1.csv##row3> ;
        <http://www.w3.org/1999/02/22-rdf-syntax-ns#_4>
                <file:/Users/ed4565/Development/sparql-anything/sandbox/formats/1.csv##row4> .

<file:/Users/ed4565/Development/sparql-anything/sandbox/formats/1.csv##row1>
        <http://www.w3.org/1999/02/22-rdf-syntax-ns#_1>
                "A" ;
        <http://www.w3.org/1999/02/22-rdf-syntax-ns#_2>
                "B" ;
        <http://www.w3.org/1999/02/22-rdf-syntax-ns#_3>
                "C" ;
        <http://www.w3.org/1999/02/22-rdf-syntax-ns#_4>
                "D" .

<file:/Users/ed4565/Development/sparql-anything/sandbox/formats/1.csv##row4>
        <http://www.w3.org/1999/02/22-rdf-syntax-ns#_1>
                "A3" ;
        <http://www.w3.org/1999/02/22-rdf-syntax-ns#_2>
                "B3" ;
        <http://www.w3.org/1999/02/22-rdf-syntax-ns#_3>
                "C3" ;
        <http://www.w3.org/1999/02/22-rdf-syntax-ns#_4>
                "D3" .

<file:/Users/ed4565/Development/sparql-anything/sandbox/formats/1.csv##row2>
        <http://www.w3.org/1999/02/22-rdf-syntax-ns#_1>
                "A1" ;
        <http://www.w3.org/1999/02/22-rdf-syntax-ns#_2>
                "B1" ;
        <http://www.w3.org/1999/02/22-rdf-syntax-ns#_3>
                "C1" ;
        <http://www.w3.org/1999/02/22-rdf-syntax-ns#_4>
                "D1" .



```

... which BTW is not great, the hash after the URI is duplicated ...

**Comment by enridaga** [comment]
... with `xyz:csv.headers true` ...
```
<file:/Users/ed4565/Development/sparql-anything/sandbox/formats/1.csv##row3>
        xyz:A   "A3" ;
        xyz:B   "B3" ;
        xyz:C   "C3" ;
        xyz:D   "D3" .

<file:/Users/ed4565/Development/sparql-anything/sandbox/formats/1.csv##row2>
        xyz:A   "A2" ;
        xyz:B   "B2" ;
        xyz:C   "C2" ;
        xyz:D   "D2" .

<file:/Users/ed4565/Development/sparql-anything/sandbox/formats/1.csv##row1>
        xyz:A   "A1" ;
        xyz:B   "B1" ;
        xyz:C   "C1" ;
        xyz:D   "D1" .
```

**Comment by luigi-asprino** [comment]
Ok, we can assume the root is the prefix for all the containers and named graphs and keep the `namespace` option only for properties and classes.

**Comment by luigi-asprino** [comment]
The convention is implemented and controlled by the FacadeX builders (not by the triplifiers anymore). I think that is convenient to make this convention explicit in the documentation.

**Comment by luigi-asprino** [comment]
However, this is not the case for the XML triplifier, which controls the namespace via the toIRI method.
Special treatment of XML URIs is required due to the fact that XML tags may come with a namespace and this needs to be preserved in RDF.
But tags/attributes without namespaces need to be treated as usual for other formats.
