### ISSUE TITLE
Performance: slicing

### ISSUE THREAD

**Issue by enridaga** [SPARQL-Anything/sparql.anything#21]
A simple way of improving usability with large files is to support a general option to 'slice' content in some ways. Some ideas: 

- by indicating the number of containers to be produced, or the maximum number of values
- by indicating the top N slots, or the bottom N
- by indicating a limit in the triples produced.

We may think of others.

**Comment by justin2004** [comment]
>A simple way of improving usability with large files

I think having an option to use an on-disk TDB instead of an in-memory graph might be the easiest approach.
Though that is less about performance and more about memory requirements.

**Comment by enridaga** [comment]
An implementation would affect the main processor as well as the Triplifier interface (maybe requiring another interface, specifically for supporting slicing).

Currently:
https://github.com/SPARQL-Anything/sparql.anything/blob/69332b35b491beb6b7d102221c71e96c41cae2fd/sparql-anything-engine/src/main/java/com/github/sparqlanything/engine/FacadeXOpExecutor.java#L195-L199

Slicing would require something like
```
Properties p = getProperties(opService.getService().getURI(), opService);
Triplifier t = getTriplifier(p);
if(t instanceof Slicer){
   Iterator<DatasetGraph> slices = t.slice(p) ; // each format with its own criteria/options
   return SliceExecutor.execute(opService.getSubOp(), input, slices, execCxt); // To stream back executions of each one of the DatasetGraph as a single QueryIterator
}else{
    // current behaviour
}
```
To implement:

- `Slicer` interface
- `SliceExecutor` probably returning on some version of `org.apache.jena.sparql.engine.iterator.QueryIteratorBase`

**Comment by enridaga** [comment]
> A simple way of improving usability with large files is to support a general option to 'slice' content in some ways. Some ideas:
> 
> * by indicating the number of containers to be produced, or the maximum number of values
> * by indicating the top N slots, or the bottom N
> * by indicating a limit in the triples produced.
> 
> We may think of others.

Reading now the initial comment I think there should be, instead, format-specific criteria for slicing. For example. CSV files can be slides row by row (or in groups of N). JSON documents may require a JsonPath expression or XML docs an XPath, and HTML doc a CSS selector, etc...

**Comment by enridaga** [comment]
Need testing, prepared with #200

**Comment by enridaga** [comment]
This is implemented by the CSV triplifier. Will take care of other formats in separate issues.

**Comment by enridaga** [comment]
Reopening because of a bug happening with some query forms
