### ISSUE TITLE
Function to build arbitrary typed literals

### ISSUE THREAD

**Issue by enridaga** [SPARQL-Anything/sparql.anything#218]
It looks like the only way to build a typed literal from a variable is to use any of the XSD functions as casting operators. However, sometimes we don't want to cast the string value or we want to attach custom datatypes...

**Comment by justin2004** [comment]
is this different than [strdt()](https://www.w3.org/TR/sparql11-query/#func-strdt)?

**Comment by enridaga** [comment]
> is this different than [strdt()](https://www.w3.org/TR/sparql11-query/#func-strdt)?

Ah ah ah! No difference at all!  I could not find it in the spec and it took 2 minutes to implement it ... one difference though is that this function behaves as STRDT and STRLANG depending on the input type. Well, we have it now ...
