### ISSUE TITLE
Support blank space in option values

### ISSUE THREAD

**Issue by enridaga** [SPARQL-Anything/sparql.anything#22]

**Comment by justin2004** [comment]
I think #83 might address this.

Because you can do things like:
`fx:properties fx:location "/mnt/some folder name/a.ttl"`
but you can't 
`fx:properties fx:location ?loc`

**Comment by luigi-asprino** [comment]
I think that this is addressed by [passing the options in the BGP](https://github.com/SPARQL-Anything/sparql.anything#passing-triplification-options-via-basic-graph-pattern)
