### ISSUE TITLE
Close all input streams

### ISSUE THREAD

**Issue by enridaga** [SPARQL-Anything/sparql.anything#239]
`Triplifier.getInputStream` is processed in many ways without appropriate auto-closing syntax

**Comment by enridaga** [comment]
Re-opening, as there are some InputStreams that should be closed when iterators finish off (what to do when they are not traversed in full?)

**Comment by luigi-asprino** [comment]
I went through all the triplifiers. Some of the input streams were already closed.
I managed to close most of the input streams.
I couldn't figure out a way to close the streams in the triplifiers for JSON and XML formats.
@enridaga, could you have a look at those?

**Comment by luigi-asprino** [comment]
Essentially, I couldn't figure out how to close the input streams when slicing is enabled.
[6892c0c](https://github.com/SPARQL-Anything/sparql.anything/commit/6892c0ca0174cdabc333f59cadb639ebb2b519d5) changes the signature of the method Slicer.slice(Properties) which now returns CloseableIterable<Slice>.
This interface provides a close method which can be implemented to close the input stream once the traversal of the input is terminated.
