### ISSUE TITLE
Read from STDIN

### ISSUE THREAD

**Issue by mielvds** [SPARQL-Anything/sparql.anything#244]
From a prior discussion:

> aha I see! Well too bad you can't do `fx -q imma-artists.sparql -o imma-artists.xml -f xml | fx -q imma-artist.sparql - -p "artists/?artistNickname.jsonld" -f json` :)

I haven't thought of getting STDIN, not impossible, but it would probably look more like:
```
fx -q imma-artists.sparql -f xml | fx -q imma-artist.sparql -i -p "artists/?artistNickname.jsonld" -f json` -- where -i without argument would attempt to catch STDIN...
```
_Originally posted by @enridaga in https://github.com/SPARQL-Anything/sparql.anything/discussions/213#discussioncomment-2525256_

Could stdin be implemented, for instance for piping JSON into SA? 

Expected behaviour:
- other that the source of input, it should behave the same as reading the data from file
- an empty `-i` means reading from stdin
- when `-i` is empty,`-f` is mandatory and the CLI should complain if it's missing.

And I don't know how useful this is, but perhaps something like

```
    SERVICE <x-sparql-anything:> {
        fx:properties fx:location <x-sparql-anything:stdin> .
        ?tvSeries xyz:name ?seriesName .
        ?tvSeries xyz:stars ?star .
        ?star fx:anySlot "Courteney Cox" .
    }
```

**Comment by luigi-asprino** [comment]
[6978afc](https://github.com/SPARQL-Anything/sparql.anything/commit/6978afccb904f761565ce85a4f31419dd76a71fa) introduces the `read-from-std-in` option which allows users to pass the data source through the standard input channel.
It is a boolean option and its default value is false.
When it is set as `true` the engine reads from stdin and sets the input as value for the [`content` option](https://github.com/SPARQL-Anything/sparql.anything/blob/v1.0-DEV/Configuration.md#content)
Therefore, the input from the std is processed as inline content (and the inline content is possibly overwritten by the input from the std in).
