### ISSUE TITLE
Use cases for the browser-related HTML options

### ISSUE THREAD

**Issue by luigi-asprino** [SPARQL-Anything/sparql.anything#257]
Hi,

I'm collecting use cases for each format-specific option.
This issue is of course related to #201 .
@justin2004 or @enridaga, could you give me some examples of the browser-related HTML options.
You can include the examples in the page dedicated to HTML https://github.com/SPARQL-Anything/sparql.anything/blob/v0.8-DEV/format/HTML.md
The section dedicated to each option has to be structured as the options [html.selector](https://github.com/SPARQL-Anything/sparql.anything/blob/v0.8-DEV/format/HTML.md#htmlselector) or [html.metadata](https://github.com/SPARQL-Anything/sparql.anything/blob/v0.8-DEV/format/HTML.md#htmlmetadata) (but I've already sketched the skeleton of such sections)
Thanks!

**Comment by justin2004** [comment]
hey @luigi-asprino ,

i use all these options
```
fx:properties fx:html.browser
fx:properties fx:html.browser.screenshot
fx:properties fx:html.browser.wait
fx:properties fx:http.header.User-Agent
fx:properties fx:http.header.Cookie
```

in https://github.com/justin2004/weblog/tree/master/scraping_with_sparql.

**Comment by luigi-asprino** [comment]
Great! I forgot that those properties were used there, thanks!
I have referenced the post from the HTML page.
I think we can close the issue.
