### ISSUE TITLE
Implement a single strategy for transforming keys into safe local names of URIs

### ISSUE THREAD

**Issue by luigi-asprino** [SPARQL-Anything/sparql.anything#259]
This relates to #246.

I think that the best way to do that is to delegate transformation to [Triplifier.toSafeURIString(String)](https://github.com/SPARQL-Anything/sparql.anything/blob/7ae4b178ed1ff7bb6ade612bf7b4f205e1418588/sparql-anything-model/src/main/java/com/github/sparqlanything/model/Triplifier.java#L188) method.
Essentially, the method does the percent encoding of the string, but additional safe standard transformation (e.g. replacing " " with "_") can be implemented there and reflected in all the triplifiers.

These strategies should be included in the documentation as well (cf. #201 ).

Finally, this is something which could be also controlled by the user via a dedicated option (e.g. default-char-for-blanks=)

**Comment by luigi-asprino** [comment]
With https://github.com/SPARQL-Anything/sparql.anything/commit/00f3d7a08bc8949b2c050c9c11250ac72df5e01f , triplifiers delegate the string sanification to the method FacadeXBuilder.addValue which, in turn, delegates the sanification to Triplifier.toSafeURI

**Comment by enridaga** [comment]
Is this one resolved?

**Comment by luigi-asprino** [comment]
Yes.. we can close it
