### ISSUE TITLE
Helper Function for returning the corresponding integers from container membership Properties

### ISSUE THREAD

**Issue by MarcoR1791** [SPARQL-Anything/sparql.anything#272]
It would be useful to have a specific function that returns the integer part of the container membership properties. This would be useful for example for ordering the results of queries. 

This is currently possible with SPARQL but it is unfortunately rather verbose. For example:
```
BIND ( xsd:int(REPLACE( STR(?mPropPart), STR(rdf:_), "") ) as ?measureCount )
```

**Comment by enridaga** [comment]
We can implement a new function `fx:cardinal` to get the integer from a container membership property.
