### ISSUE TITLE
Generate triples with the same bnode on different construct template projections

### ISSUE THREAD

**Issue by enridaga** [SPARQL-Anything/sparql.anything#273]
While playing with #271 I found an interesting issue when one wants to generate triples with the same bnode on different construct template projections. 

At the moment, a new bnode is generated for every projection, even if we use the `BNODE` function. This is reproduced as follows:

```csv
c1,c2
b0,A
b0,B
b0,C
b0,D
b0,E
b1,A
b2,B
b3,C
b4,D
b5,E
```

query:

```sparql
PREFIX ex: <http://example/> 
PREFIX fx:  <http://sparql.xyz/facade-x/ns/>
PREFIX xyz: <http://sparql.xyz/facade-x/data/>

CONSTRUCT {
 ?bnode ex:p ?A
} WHERE {
 SERVICE <x-sparql-anything:> {
	fx:properties fx:location "./data.csv" ; fx:csv.headers true .
 	[] xyz:c1 ?b0 ; xyz:c2 ?A
 }
 BIND ( BNODE ( ?b0 ) as ?bnode ) 
}
```

result:

```turtle
@prefix ex:  <http://example/> .
@prefix fx:  <http://sparql.xyz/facade-x/ns/> .
@prefix xyz: <http://sparql.xyz/facade-x/data/> .

[ ex:p    "C" ] .
[ ex:p    "E" ] .
[ ex:p    "A" ] .
[ ex:p    "C" ] .
[ ex:p    "B" ] .
[ ex:p    "D" ] .
[ ex:p    "B" ] .
[ ex:p    "D" ] .
[ ex:p    "E" ] .
[ ex:p    "A" ] .
```

A new bnode is created for each one of them, while I was expecting that the bnode identifier would join the relevant triples on `b0`.

This may or may be not wrong depending on how we consider the projected construct graph.

This is not a big problem as we can certainly use IRIs for such use case (and in general, we should!)

However, maybe if we can write a function that supports this behaviour we could fill this gap...

**Comment by enridaga** [comment]
This is implemented in a new function `fx:bnode`. Usage is as follows:

```sparql
PREFIX ex: <http://example/> 
PREFIX fx:  <http://sparql.xyz/facade-x/ns/>
PREFIX xyz: <http://sparql.xyz/facade-x/data/>

CONSTRUCT {
 ?bnode ex:p ?A
} WHERE {
 SERVICE <x-sparql-anything:> {
	fx:properties fx:location "./data.csv" ; fx:csv.headers true .
 	[] xyz:c1 ?b0 ; xyz:c2 ?A
 }
 BIND ( fx:bnode ( ?b0 ) as ?bnode ) 
}
```

With `fx -q query.sparql -f ttl` you get:

```turtle

@prefix ex:  <http://example/> .
@prefix fx:  <http://sparql.xyz/facade-x/ns/> .
@prefix xyz: <http://sparql.xyz/facade-x/data/> .

[ ex:p    "D" ] .

[ ex:p    "A" ] .

[ ex:p    "C" ] .

[ ex:p    "E" ] .

[ ex:p    "B" , "C" , "E" , "D" , "A" ] .

[ ex:p    "B" ] .
```

**Comment by enridaga** [comment]
The new function behaves as intended but it is worth also looking into how Jena developers react to the issue referred to here https://github.com/SPARQL-Anything/sparql.anything/issues/271#issuecomment-1185497609

**Comment by justin2004** [comment]
Got a [helpful reply](https://issues.apache.org/jira/browse/JENA-2340) back from the Jena developers.
