### ISSUE TITLE
README -- supported formats

### ISSUE THREAD

**Issue by justin2004** [SPARQL-Anything/sparql.anything#274]
If someone doesn't scroll all the way through the README they might not see the tool supports YAML, DOCx, etc. because they do not appear near the top:

---
A detailed description of the interpretation can be found in the following page:

[JSON](https://github.com/SPARQL-Anything/sparql.anything/blob/v0.8-DEV/formats/JSON.md)
[HTML](https://github.com/SPARQL-Anything/sparql.anything/blob/v0.8-DEV/formats/HTML.md)
[CSV](https://github.com/SPARQL-Anything/sparql.anything/blob/v0.8-DEV/formats/CSV.md)
[XML](https://github.com/SPARQL-Anything/sparql.anything/blob/v0.8-DEV/formats/XML.md)
[Binary](https://github.com/SPARQL-Anything/sparql.anything/blob/v0.8-DEV/formats/Binary.md)
[TXT](https://github.com/SPARQL-Anything/sparql.anything/blob/v0.8-DEV/formats/TXT.md)
[Markdown](https://github.com/SPARQL-Anything/sparql.anything/blob/v0.8-DEV/formats/Markdown.md)
---

Perhaps the complete list of formats should be near the top of the README even if some of the formats don't have format specific options.

**Comment by luigi-asprino** [comment]
Hi, 
we are working on improving the documentation and lightening the README file by creating a dedicated page for each format.
This is taking longer than I imagined, but I think that is needed.
I can maybe add pointers to the sections of the README for the missing formats.

**Comment by luigi-asprino** [comment]
Closed via [ee1b2c9](https://github.com/SPARQL-Anything/sparql.anything/commit/ee1b2c91ee479fcf086cd203f58e3573e25f06cf)
