### ISSUE TITLE
JSON object values not working with numbers

### ISSUE THREAD

**Issue by thabils** [SPARQL-Anything/sparql.anything#284]
The current query doesn't behave as expected when there are objects values that are not a string (number in this case).
```
PREFIX fx:  <http://sparql.xyz/facade-x/ns/>
PREFIX xyz: <http://sparql.xyz/facade-x/data/>
base  <http://example.com/base/> 

CONSTRUCT
  {
    ?subject0 <http://example.com/id> ?0 .
 }
WHERE
  {
    SERVICE <x-sparql-anything:location=test_cases/JSON/RMLTC0002a-JSON/student.json>
      {
      	?s0   xyz:students/fx:anySlot ?iterator0 . 
        ?iterator0  xyz:ID    ?0;
        bind(uri(concat(str("http://example.com/"),encode_for_uri(?0))) as ?subject0)
      }
  }
```

with student.json:
`
{
  "students": [
    {
      "ID": 10,
      "Name":"Venus"
    }
  ]
}
`

It generates an empty output file and doesn't give any errors.

But when we change student.json to (change number to string):
`{
  "students": [
    {
      "ID": "10",
      "Name":"Venus"
    }
  ]
}`

It does generate the expected output:
`<http://example.com/10> <http://example.com/id> "10" .`

**Comment by luigi-asprino** [comment]
Hi,

Thanks for reporting this. 
I'm unsure if it is something wrong with SPARQLAnything or if it is a misuse of the function [encode_for_uri which expects a string](https://www.w3.org/TR/xpath-functions/#func-encode-for-uri) (instead of an integer).


In fact, if you transform ?0 into a string 

```
BASE    <http://example.com/base/>
PREFIX  xyz:  <http://sparql.xyz/facade-x/data/>
PREFIX  fx:   <http://sparql.xyz/facade-x/ns/>

CONSTRUCT 
  { 
    ?subject0 <http://example.com/id> ?0 .
  }
WHERE
  { SERVICE <x-sparql-anything:location=file:/Users/lgu/workspace/SPARQLAnything/sparql.anything/sparql-anything-it/target/test-classes/issues/issue284.json>
      { ?s0 xyz:students/fx:anySlot ?iterator0 .
        ?iterator0  xyz:ID  ?0
        BIND(uri(concat(str("http://example.com/"), encode_for_uri(str(?0)))) AS ?subject0)
      }
  }
```

it works as expected

```
@prefix fx:  <http://sparql.xyz/facade-x/ns/> .
@prefix xyz: <http://sparql.xyz/facade-x/data/> .

<http://example.com/10>
        <http://example.com/id>  "10"^^<http://www.w3.org/2001/XMLSchema#int> .

```

I couldn't find any indication of what happens in SPARQL in case of exception. It seems that it just doesn't give any result and therefore the SPARQL engine doesn't bind the variable ?subject0.

**Comment by enridaga** [comment]
> I couldn't find any indication of what happens in SPARQL in case of exception. It seems that it just doesn't give any result and therefore the SPARQL engine doesn't bind the variable ?subject0.

In my experience, every time a function returns a non-value all the other functions in the chain will do as well so that the resulting BIND variable results unbound. I think those should raise exceptions but this is not a decision for us to take. 

> `BIND(uri(concat(str("http://example.com/"), encode_for_uri(str(?0)))) AS ?subject0)`

Anyway, have you considered using the commodity function `fx:entity` instead, it will do the casting for you:

`BIND( fx:entity ("http://example.com/"), ?0 ) AS ?subject0 )`

**Comment by luigi-asprino** [comment]
Of course, with fx:entity is a way easier :-)

```
BASE    <http://example.com/base/>
PREFIX  xyz:  <http://sparql.xyz/facade-x/data/>
PREFIX  fx:   <http://sparql.xyz/facade-x/ns/>

CONSTRUCT 
  { 
    ?subject0 <http://example.com/id> ?0 .
  }
WHERE
  { SERVICE <x-sparql-anything:location=file:/Users/lgu/workspace/SPARQLAnything/sparql.anything/sparql-anything-it/target/test-classes/issues/issue284.json>
      { ?s0 xyz:students/fx:anySlot ?iterator0 .
        ?iterator0  xyz:ID  ?0
        BIND(fx:entity("http://example.com/", ?0) AS ?subject0)
      }
  }
```

Tested, it gives the same result.

**Comment by thabils** [comment]
> I couldn't find any indication of what happens in SPARQL in case of exception. It seems that it just doesn't give any result and therefore the SPARQL engine doesn't bind the variable ?subject0.

Ah yes that explains it. Thanks for the quick reply and fix.

**Comment by thabils** [comment]
> Of course, with fx:entity is a way easier :-)
> 
> ```
> BASE    <http://example.com/base/>
> PREFIX  xyz:  <http://sparql.xyz/facade-x/data/>
> PREFIX  fx:   <http://sparql.xyz/facade-x/ns/>
> 
> CONSTRUCT 
>   { 
>     ?subject0 <http://example.com/id> ?0 .
>   }
> WHERE
>   { SERVICE <x-sparql-anything:location=file:/Users/lgu/workspace/SPARQLAnything/sparql.anything/sparql-anything-it/target/test-classes/issues/issue284.json>
>       { ?s0 xyz:students/fx:anySlot ?iterator0 .
>         ?iterator0  xyz:ID  ?0
>         BIND(fx:entity("http://example.com/", ?0) AS ?subject0)
>       }
>   }
> ```
> 
> Tested, it gives the same result.

This indeed looks like a better way to do it, will use it from now on :)

**Comment by luigi-asprino** [comment]
Great :-) I think we can close this issue now

**Comment by justin2004** [comment]
also remember that with [strdt()](https://www.w3.org/TR/sparql11-query/#func-strdt) you can cast to any datatype you want.

**Comment by enridaga** [comment]
Just a note that JSON numbers will be tagged `xsd:decimal` after #620
