### ISSUE TITLE
IT tests failing after executor refactoring

### ISSUE THREAD

**Issue by enridaga** [SPARQL-Anything/sparql.anything#298]
As the summary says

**Comment by enridaga** [comment]
Apparently, after using the ondisk option, subsequent tests are failing. I isolated `testIssue280` and `testIssue284`. 284 runs smoothly if executed alone. The test class we are focusing on now is IssuesTest2

**Comment by luigi-asprino** [comment]
the BaseFacadeXGraphBuilder uses static fields https://github.com/SPARQL-Anything/sparql.anything/blob/70c402a7093a8b7d82b6840323f6cc6422122201/sparql-anything-model/src/main/java/com/github/sparqlanything/model/BaseFacadeXGraphBuilder.java#L42

maybe the problem depends on this?

**Comment by luigi-asprino** [comment]
This
https://github.com/SPARQL-Anything/sparql.anything/blob/70c402a7093a8b7d82b6840323f6cc6422122201/sparql-anything-model/src/main/java/com/github/sparqlanything/model/BaseFacadeXGraphBuilder.java#L58
Shouldn't it be !BaseFacadeXGraphBuilder.previousTDB2Path.equals("")?

**Comment by luigi-asprino** [comment]
This [8c6de26](https://github.com/SPARQL-Anything/sparql.anything/commit/8c6de265aca3031651fcbccec34b386509399cd4) removes the static fields from the class BaseFxGraphBuilder.
Tests in IssuesTest2 don't fail anymore

**Comment by luigi-asprino** [comment]
We can close this issue if there are no other tests failing.

**Comment by luigi-asprino** [comment]
I close this issue as it is completed via [f1355c0](https://github.com/SPARQL-Anything/sparql.anything/commit/f1355c0e8d9e846e43e3e7a53711e963bd9cd99b)
