### ISSUE TITLE
Consistent parameter names in URIs

### ISSUE THREAD

**Issue by enridaga** [SPARQL-Anything/sparql.anything#3]
I suggest using `location`, `namespace` (applied to domain specific properties/types), `media-type` for general-purpose parameters and specify type-specific ones using, for example, `csv.format=DEFAULT` or `json.root` ...

**Comment by enridaga** [comment]
General properties:

 - location*
 - media-type (default guess from extension)
 - namespace (default uses location)
 - root (default uses location)
 - blank-nodes (default true)

CSV specific:

 - csv.format (default DEFAULT) -> ref apache commons.csv
 - csv.headers (defaults false)

**Comment by luigi-asprino** [comment]
I think that this can be closed
