### ISSUE TITLE
[Spreadsheet] Composite cell values

### ISSUE THREAD

**Issue by enridaga** [SPARQL-Anything/sparql.anything#308]
Currently, cell values are limited to simple datatypes such as number, string, boolean.
However, sometimes cell include richer content, for example, links.
We could apply the facade to such content and make those links accewssible.

**Comment by luigi-asprino** [comment]
Could you post an example?

**Comment by enridaga** [comment]
I created a test and developed a basic transformation (which should be reviewed for consistency, some decisions I am not 100% sure)

**Comment by enridaga** [comment]
The general point is to support the case where cells require a complex description, I have added a property `spreadsheet.composite-values` that makes the cell be triplified as a container rather than a literal value.

**Comment by luigi-asprino** [comment]
I also made the triplifier extract comments that might be attached to the cells

**Comment by luigi-asprino** [comment]
I've also updated the documentation https://github.com/SPARQL-Anything/sparql.anything/blob/v0.9-DEV/formats/Spreadsheet.md#spreadsheetcomposite-values

**Comment by enridaga** [comment]
I think this seems ready to go, I will move it to v0.8.1
