### ISSUE TITLE
ASK Query CLI Output

### ISSUE THREAD

**Issue by MarcoR1791** [SPARQL-Anything/sparql.anything#320]
When executing an ASK query without specifying either f = 'xml' or f = 'json', only the output of StdErr can be seen.
Nothing else is printed to the command line.

**Comment by enridaga** [comment]
It looks like the Jena ResultSetFormatter does not work properly with boolean, this is where it's applied: https://github.com/SPARQL-Anything/sparql.anything/blob/55ad0f277c7891d24051b666f00e2d59a5147167/sparql-anything-cli/src/main/java/com/github/sparqlanything/cli/SPARQLAnything.java#L107

**Comment by lucic71** [comment]
Still reproducible for me with v0.8.1 and the following command:
```
java -jar sparql-anything-0.8.1.jar -q ask.sparql
```

Where ask.sparql has a simple ASK query. However it works if I add -f text.

**Comment by enridaga** [comment]
Thanks for reporting, @lucic71 -- you're right; I just reproduced it with v0.8.1. I am unsure why this happened, but I can see it working correctly with the current development branch `v0.9-DEV`:

```bash
$ fx -q "ASK {[] ?p []}"
[main] INFO com.github.sparqlanything.cli.SPARQLAnything - SPARQL anything
_askResult
false

```
