### ISSUE TITLE
XML parser bug

### ISSUE THREAD

**Issue by lennertvandevelde** [SPARQL-Anything/sparql.anything#325]
### Bug summary

Given the XML file above, and running a sparql-anything query which matches `dct:identifier` with a value in a different file, the query produces no result. Note that the beginning of the line contains a U+200B, zero-width space, invisible character (but which validates as a correct xml). 
![image](https://user-images.githubusercontent.com/61053080/208668650-6d2b460f-20de-4eae-bee2-7f93dc9474e1.png)
The HEX value of the produced value is `200B757569642D6...`, meaning that the parser prepends the zero-width space to the value of the element.

Removing this U+200B character produces the correct result:
![image](https://user-images.githubusercontent.com/61053080/208668683-1808673e-be08-4157-a0fe-f00d385f0e4c.png)
This time the HEX value produced is `757569642D6...`.

### Version

```Text
Version:             0.8.0
```

**Comment by lennertvandevelde** [comment]
The `saaa` string on line 20 was accidental, but it shows that anything outside element tags is also prepended to the value.

**Comment by enridaga** [comment]
Hi! Do you mind attaching the original file so we can reproduce the issue locally?

**Comment by lennertvandevelde** [comment]
Minimal reproducible example: 

### XML file:
```
<?xml version='1.0' encoding='UTF-8'?>
<metadata xmlns:dct="http://purl.org/dc/terms/"
		  xmlns:xs="http://www.w3.org/2001/XMLSchema/"
		  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance/">
  THIS_TEXT_IS_OUTSIDE_SUBJECT<dct:subject>THIS_TEXT_IS_INSIDE_SUBJECT</dct:subject>
  ​
</metadata>
```

### SPARQL-query:
```
PREFIX xsi: <http://www.w3.org/2001/XMLSchema-instance#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX fx: <http://sparql.xyz/facade-x/ns/> 
PREFIX dct: <http://purl.org/dc/terms/>

CONSTRUCT
    {
        ?s ?p ?o .
    }
WHERE
    { 
        SERVICE <x-sparql-anything:location=./data/dc.xml> { 
            ?s ?p ?o .
        }
    }   
```

### Results:
```
@prefix dct: <http://purl.org/dc/terms/> .
@prefix fx:  <http://sparql.xyz/facade-x/ns/> .
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix xsi: <http://www.w3.org/2001/XMLSchema-instance#> .

[ rdf:type  <http://sparql.xyz/facade-x/data/metadata> , fx:root ;
  rdf:_1    [ rdf:type  dct:subject ;
              rdf:_1    "THIS_TEXT_IS_OUTSIDE_SUBJECTTHIS_TEXT_IS_INSIDE_SUBJECT"
            ] ;
  rdf:_2    "​"
] .
```

**Comment by lennertvandevelde** [comment]
Note that:
- the text outside the dct:subject element is appended to it when converting to triples
-  `rdf:_2` is present here, because the line under the subject contains a `U+200B` zero-width space character

**Comment by enridaga** [comment]
The first issue should be fixed now with [this commit](https://github.com/SPARQL-Anything/sparql.anything/commit/f5cf509bb7ed16bcfb1649113d99413e349eed32).

**Comment by enridaga** [comment]
Not sure how to treat that char; the XML is valid, and that character is neither a new line nor a white space, at least when the file is treated with the default charset (UTF-8). 
When the string is non-empty after trimming, we capture the content, e.g.:

https://github.com/SPARQL-Anything/sparql.anything/blob/f5cf509bb7ed16bcfb1649113d99413e349eed32/sparql-anything-xml/src/main/java/com/github/sparqlanything/xml/XMLTriplifier.java#L282

**Comment by lennertvandevelde** [comment]
I think the commit would fix the issue of the zero-width space character in our case as well, because the character always precedes an XML-tag. [This answer](https://superuser.com/a/1764151) provides a Unicode Regex Patern for all formatting zero width whitespace characters, including `U+200B`.

**Comment by enridaga** [comment]
Great, I am going to close this one, then.
