### ISSUE TITLE
Upgrade Jena to 4.7 ?

### ISSUE THREAD

**Issue by enridaga** [SPARQL-Anything/sparql.anything#326]
To review the changes from the current version:

https://github.com/apache/jena/compare/jena-4.2.0...jena-4.7.0

**Comment by luigi-asprino** [comment]
Recap of changes made for issue #326
- Implement visit(OpLateral) for query visitor, see https://jena.apache.org/documentation/query/lateral-join.html
- Change how the RDFTriplifier loads RDF serialisation 
- Initialise ARQ context before registering OpExecutor
- Replace ReaderRIOT for JSONLD (see #339)
- Implement close() in ArgValuesAsResultSet
- JSONLD RIOT parsers for JSONLD10 and JSONLD11 require extension .jsonld10 or .jsonld11 
- Ensure reading transaction before printing the size of the dataset (i.e. number of the graphs in the dataset graph)

**Comment by luigi-asprino** [comment]
Fuseki version is still 4.2.0

**Comment by luigi-asprino** [comment]
I've created a POM property (named jena.version) for controlling the Jena Version
