### ISSUE TITLE
`-o` adds suffix `-1` to output file

### ISSUE THREAD

**Issue by VladimirAlexiev** [SPARQL-Anything/sparql.anything#331]
Something strange: output is not written to the file specified with `-o` but to a slightly different file:
- `-o foo` -> `foo-1`
- `-o foo.ttl` -> `foo-1.ttl`

Version: sparql.anything-0.8.1.jar

**Comment by enridaga** [comment]
That is supposed to happen when there are parameters (and multiple executions). Can you please show the full command line?

**Comment by justin2004** [comment]
this also happened for me.

```python
import pysparql_anything as sa
engine = sa.SparqlAnything()
engine.run(
        query="transformations/airlines.rq",
        format="ttl",
        values={
            "location" : "csv/airlines.csv"
        },
        output="output_from_py/airlines.ttl"
    )
```

produces
```
airlines-1.ttl
```

it would be ideal if it didn't add the `-1`

**Comment by luigi-asprino** [comment]
[d42b103](https://github.com/SPARQL-Anything/sparql.anything/commit/d42b10336bdd015a4024cc99840c4ec05d6634d5) includes a test for this issue and it appears that it's no longer an issue.
Please let me know if you are still experiencing the problem, and if so, please reopen this issue.

**Comment by luigi-asprino** [comment]
This occurs only when `-v` argument is used.

**Comment by luigi-asprino** [comment]
[f7c6fcc](https://github.com/SPARQL-Anything/sparql.anything/commit/f7c6fcc1005880f33eaea6154e1e8b3e3a7e9b88) fixes the problem and introduces a test
