### ISSUE TITLE
[Documentation] Clarify `json.path` in docs

### ISSUE THREAD

**Issue by justin2004** [SPARQL-Anything/sparql.anything#333]
in the json docs:
https://github.com/SPARQL-Anything/sparql.anything/blob/v0.9-DEV/formats/JSON.md

we mostly talk about using json.path and i think that misleads users into thinking that they should use it to remodel their data into RDF.
see #332 

i wonder if we should use the example in #332 as the first example and only at the bottom demonstrate json.path (which i hardly ever use)?

**Comment by enridaga** [comment]
Agreed 100% - the json.path option is so misleading that I almost regret it 😆

**Comment by enridaga** [comment]
> i wonder if we should use the example in https://github.com/SPARQL-Anything/sparql.anything/issues/332 as the first example and only at the bottom demonstrate json.path (which i hardly ever use)?

I added two examples without json.path, including yours.

**Comment by enridaga** [comment]
This seems to be addressed.
