### ISSUE TITLE
[CLI] Support extension .json as JSON-LD content with option `--load`

### ISSUE THREAD

**Issue by enridaga** [SPARQL-Anything/sparql.anything#339]
Sometimes JSON-LD content is delivered with the extension `.json`, which raises this error:
```
Problem was: Failed to determine the content type: (URI=file:///Users/ed4565/Development/sparql-anything/sparql.anything/sparql-anything-cli/target/test-classes/JsonldTest.json : stream=null)
```

**Comment by luigi-asprino** [comment]
Jena 4.7.0 (see #326) replaced the JSONLDReader class with LangJSONLD11 and LangJSONLD10.
Which one should be used?

**Comment by luigi-asprino** [comment]
I went for JSONLD 1.1.

**Comment by enridaga** [comment]
This change introduced a bug in the RDFTriplifier, because now the content type application/ld+json returns the Lang JSON instead of JSONLD.
