### ISSUE TITLE
How can I add external data to an existing Knowledge Graph

### ISSUE THREAD

**Issue by ejaz-karim** [SPARQL-Anything/sparql.anything#346]
I am querying a .xlsx file with the CONSTRUCT and WHERE command and I have an existing .ttl output. I would like to add an additional SERVICE call to Wikidata or any other websites/encyclopedia/knowledge bases in order to add data relating to my current Knowledge graph output file. The reason I can't is because the data from Wikidata is not in the .ttl format (rdf). 
May you please tell me the necessary steps required to add this data to my existing knowledge graph.
Here is my query file:
```
PREFIX xyz: <http://sparql.xyz/facade-x/data/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX fx: <http://sparql.xyz/facade-x/ns/>
PREFIX pfn: <https://polifonia-project.eu/resource/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX wdt: <http://www.wikidata.org/prop/direct/> 

CONSTRUCT {
    ?pilot_iri a pfn:pilot ;
        rdfs:label ?pilot ;
        pfn:hasPart ?part_iri ;
        pfn:hasQuestion ?question_iri ;
        pfn:hasAnswer ?answer_iri .
    
    ?part_iri pfn:hasQuestion ?question_iri ;
        rdfs:label ?part ;
        pfn:hasQuestion ?question_iri .

    ?question_iri pfn:hasAnswer ?answer_iri ;
        rdfs:label ?question .
    
    ?answer_iri rdfs:label ?answer ;
        rdfs:seeAlso ?question_iri .
}
WHERE {
    SERVICE <x-sparql-anything:file:./surveyExtraction.xlsx> {        
        ?r a fx:root ;
            ?p ?row .
        ?row rdf:_1 ?part ;
            rdf:_2 ?question ;
            rdf:_3 ?pilot ;
            rdf:_4 ?answer .
    }
    BIND(IRI(CONCAT("https://polifonia-project.eu/resource/pilot/", STR(ENCODE_FOR_URI(?pilot)))) as ?pilot_iri)
    BIND(IRI(CONCAT("https://polifonia-project.eu/resource/part/", STR(ENCODE_FOR_URI(?part)))) as ?part_iri)
    BIND(IRI(CONCAT("https://polifonia-project.eu/resource/question/", STR(ENCODE_FOR_URI(SHA1(?question))))) as ?question_iri)
    BIND(IRI(CONCAT("https://polifonia-project.eu/resource/answer/", STR(ENCODE_FOR_URI(SHA1(?answer))))) as ?answer_iri)
}
```
Current output:
```
<https://polifonia-project.eu/resource/answer/792d5fd4651d46bf2d6e3af2eee9c3883a000039>
        rdfs:label    "Musicology " ;
        rdfs:seeAlso  <https://polifonia-project.eu/resource/question/6885ede460472ba7e428311224a67e17251b26da> .
```

Desired output
```
<https://polifonia-project.eu/resource/answer/792d5fd4651d46bf2d6e3af2eee9c3883a000039>
        rdfs:label    "Musicology " ;
        rdfs:seeAlso  <https://polifonia-project.eu/resource/question/6885ede460472ba7e428311224a67e17251b26da> ;
        wd:label <data relating to Musicology> .
```

**Comment by justin2004** [comment]
below is an example of how you could do this (you'll have to turn it into a construct query).
but notice the output contains data from wikidata and the csv file.

you do need a way of doing identity resolution and for this query i just used the column "thinglabel" and i used the fact that musicology is an instance of academic discipline (Q11862829) to limit the results. 

```
justin@parens$ cat 346.csv 
thinglabel,url
musicology,http://example.com/musicology
```

```sparql
curl --silent  'http://localhost:3000/sparql.anything'  \
--header "Accept: text/csv" \
--data-urlencode 'query=
PREFIX  fx:   <http://sparql.xyz/facade-x/ns/>
PREFIX  rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX  wdt:  <http://www.wikidata.org/prop/direct/>
PREFIX  xyz:  <http://sparql.xyz/facade-x/data/>
PREFIX  rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX  wd:   <http://www.wikidata.org/entity/>
SELECT  *
WHERE
  { SERVICE <x-sparql-anything:>
      { fx:properties
                  fx:location     "/app/346.csv" ;
                  fx:csv.headers  "true" .
        ?s        xyz:thinglabel  ?label ;
                  xyz:url         ?url
        BIND(strlang(?label, "en") AS ?wiki_label)
      }
    SERVICE <https://query.wikidata.org/sparql>
      { ?s0  rdfs:label  ?wiki_label ;
             wdt:P31     wd:Q11862829 ;
             wdt:P1417   ?britannica_id
      }
  }
'
```

yields:

|s     |label       |url                 |wiki\_label |s0                  |britannica\_id    |
|------|------------|--------------------|------------|--------------------|------------------|
|\_:b0 |musicology  |http://example\.com/musicology|musicology  |http://www\.wikidata\.org/entity/Q164204|topic/musicology  |

**Comment by justin2004** [comment]
@ejaz-karim does that help? or should i turn the query into a construct query?

**Comment by ejaz-karim** [comment]
The problem I am facing is that I have thousands of labels in my .ttl output. I failed to mention this in my first comment. Each label is different and some labels are long sentences. Is there a way to pull keywords from a long worded label and query those keywords. I would like to also pull information from the wikidata article or whichever source that I use, such as a description etc. That begs the question, which other online sources are suitable for Sparql Anything?
I like the example you gave but I think it would be too specific for my entire output, please tell me if that's the right approach. I would really appreciate to see a construct query that can do something like I have just mentioned. Would it be compatible with my existing construct query, or would I have to use two construct queries?

**Comment by ejaz-karim** [comment]
@justin2004 bump

**Comment by justin2004** [comment]
@ejaz-karim 

> Each label is different and some labels are long sentences.
> Is there a way to pull keywords from a long worded label and query those keywords.

It sounds like you have a entity resolution task. You can use certain words from labels during entity resolution but you have to decide which words you'll use. 

> That begs the question, which other online sources are suitable for Sparql Anything?

Anything that can give you one of the SPARQL Anything recognized formats.
[Here](https://github.com/justin2004/weblog/tree/master/dynamic_pagination_with_sparql_anything) is an example of using SPARQL Anything to talk to an API that produces xml.
[Here](https://github.com/justin2004/weblog/tree/master/blend_google_sheet_with_wikidata) is an example of using SPARQL Anything to interact with a Google Sheet.
[HTML scraping with SPARQL Anything](https://github.com/justin2004/weblog/tree/master/scraping_with_sparql).
[Date string normalization via SPARQL Anything](https://github.com/justin2004/weblog/tree/master/SPARQL_value_functions).


You might do some searching on "entity resolution" for some ideas. Once you have an approach in mind you can use SPARQL Anything to talk to the API endpoints programmatically (to get source data) and to ultimately produce your graph but you'll have to do some entity resolution in the middle.
