### ISSUE TITLE
Facade-X options as basic graph patterns

### ISSUE THREAD

**Issue by enridaga** [SPARQL-Anything/sparql.anything#35]
It could be useful to support facade-x configuration from within the SERVICE query with magic properties.

**Comment by luigi-asprino** [comment]
This should have been addressed by commit e8125a34249c9dbe9f49e9d92c2d1759f7343ce1

**Comment by enridaga** [comment]
I reopen this one to discuss my comment to e8125a3 and to wait until we have at least basic documentation of the feature in the readme

**Comment by enridaga** [comment]
Better to refer to this feature as properties in BGP rather than magic properties
Anyway, this is now documented in the readme
