### ISSUE TITLE
Document how sparql anything can be used as a library

### ISSUE THREAD

**Issue by sandervd** [SPARQL-Anything/sparql.anything#358]
Only the cli is documented, it would be useful to have API documentation when embedding sparql anything in other projects.

**Comment by justin2004** [comment]
i've only been successful embedding it in another project by using the main method as the entry point:
https://github.com/justin2004/git_to_rdf/blob/master/src/git_to_rdf/core.clj#L160

i tried to register the triplifiers with the jena library more directly but wasn't successful.

**Comment by sandervd** [comment]
Maybe it would be best to explain our use case a bit further:
We are building a streaming platform that will based on linked data. It would be great for onboarding non-linked data datastreams to our platform to be able to use sparql anything to RDFize the data.
Being able to consider SPARQL anything as sort of Jena on steroids would be ideal. 
For instance, if we would want to apply single message transforms to each message in stream, we could use prebinding of a variable to 'inject' the message being transformed into the query. It would make a nice reusable building block in out ecosystem.
I just discovered sparql anything a few days ago, and I must admit I haven't put in the necessary time to asses the feasibility of what I'm describing here :)

@justin2004
Would it be correct to assume you are also trying to achieve this 'Jena SPARQL queries on steroids' idea?

**Comment by enridaga** [comment]
So true, we should document how to use it within Java. Maybe a good starting point would be to look at how we are doing it in the integration tests, or in tests that we developed for specific issues, for example:

https://github.com/SPARQL-Anything/sparql.anything/blob/64df18501b1dfa5fb652cfe823fc735c3da8628c/sparql-anything-it/src/test/java/com/github/sparqlanything/it/IssuesTest2.java#L181-L187

**Comment by enridaga** [comment]
Also, if you are interested in using it from Python, you can look at this project https://github.com/SPARQL-Anything/PySPARQL-Anything

**Comment by sandervd** [comment]
Thank you @enridaga, this is a great help!

**Comment by justin2004** [comment]
@sandervd 

> Would it be correct to assume you are also trying to achieve this 'Jena SPARQL queries on steroids' idea?

Yes. And for that project I linked above SPARQL Anything was a great fit.
After all, SPARQL Anything is "just" Apache Jena with a custom service handler.

It _happens_ to be a very thoughtful custom service handler and Apache Jena is a great piece of software (the de facto reference RDF/SPARQL implementation).

**Comment by luigi-asprino** [comment]
Instructions on how to use SPARQL Anything as a Java Library are available here https://github.com/SPARQL-Anything/sparql.anything/blob/v1.0-DEV/JAVA_LIBRARY.md
