### ISSUE TITLE
Give file name as parameter from command line

### ISSUE THREAD

**Issue by lucic71** [SPARQL-Anything/sparql.anything#359]
Hi,

I have the following query:
```
SELECT ?s ?p ?o
WHERE {

	SERVICE <x-sparql-anything:file:///path/to/my/file> {
		?s ?p ?o
	}
}
```

And I'm running the query with the following command:
```
java -jar sparql-anything-0.8.1.jar -q q.sparql
```

Is there a way to give the filename as a command line argument and use it with something like this:
```
SELECT ?s ?p ?o
WHERE {

	SERVICE <x-sparql-anything:file://$filename> {
		?s ?p ?o
	}
}
```

From the documentation I understood that -l might be a solution for that but I couldn't use it correctly.

**Comment by luigi-asprino** [comment]
Hi,

You can use [Basil integration](https://github.com/SPARQL-Anything/sparql.anything#query-templates-and-variable-bindings-cli-only) to create a query template.

This is how the query template looks like

```
PREFIX fx: <http://sparql.xyz/facade-x/ns/>
SELECT * {
  
  SERVICE <x-sparql-anything:> {
   fx:properties fx:location ?_filepath .
   ?s ?p ?o
}

}
```

You can pass the actual file path via the -v argument

```
 java    -jar sparql-anything-0.8.1.jar -q query.sparql -v filepath=file:///Users/lgu/Desktop/test.json
```

**Comment by lucic71** [comment]
Thanks for that! Very helpful!
