### ISSUE TITLE
Utility function for "Don't produce a URI"?

### ISSUE THREAD

**Issue by alexdma** [SPARQL-Anything/sparql.anything#361]
It would be useful in my use cases to have a function that corresponds to "No URI", since the null URI `<>` is transformed to the graph URI.

For example, suppose in my data about objects I have a property `fate` whose value can be `existing`, `dispersed` or `destroyed`. Say I extract the property value and bind it to SPARQL variable `?fate`.

I want to use a SPARQL IF clause to produce an entity that represents the undoing (destruction or dispersion) of the object only if the value is _other than_ `existing`. It must _not_ produce any URI (and therefore any triples that would use it) if the value is `existing`.

I'd imagine something like

    BIND( IF( ?fate != "existing" , fx:entity(....) , fx:nothing() ) AS ?undoing )

where `fx:nothing()` leaves `?undoing` unbound and therefore a triple pattern in a CONSTRUCT like

    <object> ont:was_undone_by ?undoing

would not produce triples.

Does it sound like a sensible thing to look into?

**Comment by enridaga** [comment]
Would the following do the job?

```sparql
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX xyz: <http://sparql.xyz/facade-x/data/>
PREFIX fx:  <http://sparql.xyz/facade-x/ns/>

select * where {
    service <x-sparql-anything:> {
        fx:properties fx:content "A,B,C\n1,2,3\n" ; fx:media-type "text/csv" .
        ?s ?p ?o .
    }
    
    
    OPTIONAL { 
        FILTER (?o = 'C') .
        BIND( true AS ?isTrue ) . 
    }
}
```

It is less compact and maybe less intuitive than the solution you propose. Perhaps an `unbound()` function could make sense as well. Also something to bring to the SPARQL 1.2 WG?

**Comment by alexdma** [comment]
So if I'm doing a CONSTRUCT, I could replace `true` in that query with the expression that creates the URI, is that it?

It seems like a workable stop-gap solution, thanks! But yes, if the SPARQL 1.2 WG will consider requests for builtin functions, why not.

**Comment by justin2004** [comment]
this might work:

```
BIND( IF( ?fate != "existing" , fx:entity(....) , 1/0 ) AS ?undoing )
```

`1/0` should cause no bindings to be produced ~~ no URI

**Comment by justin2004** [comment]
@alexdma  did that work for you?

if so i think we can close this.

**Comment by alexdma** [comment]
> @alexdma did that work for you?
> 
> if so i think we can close this.

Yes, I have been using that and other undefined expressions and it does have the desired effect, even though it still feels like kind of a side effect.

Closing until the need arises for formalising it as a function.
