### ISSUE TITLE
fx:command doesn't accept shell pipelines

### ISSUE THREAD

**Issue by justin2004** [SPARQL-Anything/sparql.anything#365]
e.g.

currently this query
```sparql
SELECT  *
WHERE
  { SERVICE <x-sparql-anything:>
      { fx:properties
                  fx:command     "ps -ef | grep bash " ;
                  fx:media-type  "text/plain" .
        ?s        ?p             ?o
      } 
  }
```

produces:

|s     |p                                                |o                                   |
|------|-------------------------------------------------|------------------------------------|
|\_:b0 |http://www\.w3\.org/1999/02/22\-rdf\-syntax\-ns\#type|http://sparql\.xyz/facade\-x/ns/root|
|\_:b0 |http://www\.w3\.org/1999/02/22\-rdf\-syntax\-ns\#\_1|                                    |

but the desired output is something like:

|s     |p                   |o                                                                                                                                          |
|------|--------------------|-------------------------------------------------------------------------------------------------------------------------------------------|
|\_:b0 |http://www\.w3\.org/1999/02/22\-rdf\-syntax\-ns\#type|http://sparql\.xyz/facade\-x/ns/root                                                                                                       |
|\_:b0 |http://www\.w3\.org/1999/02/22\-rdf\-syntax\-ns\#\_1|root         257     215  0 14:01 pts/0    00:00:00 bash \-c ps \-ef

**Comment by justin2004** [comment]
i'm opening a PR now

**Comment by luigi-asprino** [comment]
Can we close this?

**Comment by justin2004** [comment]
yes, i think so.
