### ISSUE TITLE
Docker build failure?

### ISSUE THREAD

**Issue by jakob-beetz** [SPARQL-Anything/sparql.anything#370]
Dear all, thank you for this amazing project. 
I am getting an error when trying to launch the docker image.

Here is what I did:

```
D:\src\sparql.anything>docker run -v sparql-anything_playwright:/ms-playwright -v sparql-anything_m2:/root/.m2 -p 3000:3000 --rm -it -v D:/src/sparql.anything^T mvn <args> -rf :sparql-anything-it:/app sparql-anything-development
```

every build an test runs smooth until sparql-anything-it

```
[INFO] sparql-anything-cli ................................ SUCCESS [ 59.406 s]
[INFO] sparql-anything-it ................................. FAILURE [ 49.428 s]
[INFO] sparql-anything-fuseki ............................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  04:22 min
[INFO] Finished at: 2023-05-31T13:33:00Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test (default-test) on project sparql-anything-it: There are test failures.
[ERROR]
[ERROR] Please refer to /app/sparql-anything-it/target/surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR]
``` 
which results in a `io.github.sparqlanything.it.IssuesTest.txt` containing
```
-------------------------------------------------------------------------------
Test set: io.github.sparqlanything.it.IssuesTest
-------------------------------------------------------------------------------
Tests run: 21, Failures: 0, Errors: 1, Skipped: 1, Time elapsed: 8.172 sec <<< FAILURE!
testIssue295(io.github.sparqlanything.it.IssuesTest)  Time elapsed: 0.65 sec  <<< ERROR!
org.apache.jena.tdb2.TDBException: NodeTableThrift/Write
	at org.apache.jena.tdb2.store.nodetable.NodeTableTRDF.writeNodeToTable(NodeTableTRDF.java:71)
	at org.apache.jena.tdb2.store.nodetable.NodeTableNative.accessIndex(NodeTableNative.java:143)

8< ----- SNIP 8< ----- 


Caused by: org.apache.jena.atlas.RuntimeIOException: java.io.IOException: No such file or directory
	at org.apache.jena.atlas.io.IO.exception(IO.java:357)
	at org.apache.jena.dboe.base.file.BinaryDataFileRandomAccess.length(BinaryDataFileRandomAccess.java:130)
	at org.apache.jena.dboe.base.file.BinaryDataFileWriteBuffered.length(BinaryDataFileWriteBuffered.java:77)
	at org.apache.jena.dboe.trans.data.TransBinaryDataFile.length(TransBinaryDataFile.java:242)
	at org.apache.jena.tdb2.store.nodetable.NodeTableTRDF.writeNodeToTable(NodeTableTRDF.java:62)
	... 63 more
Caused by: java.io.IOException: No such file or directory
	at java.base/java.io.RandomAccessFile.length(Native Method)
	at org.apache.jena.dboe.base.file.BinaryDataFileRandomAccess.length(BinaryDataFileRandomAccess.java:129)
	... 66 more

````

Not sure where to look for the missing / missspelled file here.

I greatly appreciate any help!
Thank you again for your work.
Jakob

**Comment by justin2004** [comment]
when you are following [these](https://github.com/SPARQL-Anything/sparql.anything/blob/v0.9-DEV/BROWSER.md) instructions to run the docker container are you in a `bash` shell?

**Comment by jakob-beetz** [comment]
> when you are following [these](https://github.com/SPARQL-Anything/sparql.anything/blob/v0.9-DEV/BROWSER.md) instructions to run the docker container are you in a `bash` shell?

Hi Justin ,thank you. 
Yes, I fowllowed them verbatim (replaced the `pwd` by hard-coding the absolute path) 
All tests run smoothly up to that last-but-one  build/test.

**Comment by justin2004** [comment]
gotcha.
well we should address that error but in the meantime i bet you could run sparql anything in a container by un-commenting the 2nd CMD stanza [here](https://github.com/SPARQL-Anything/sparql.anything/blob/v0.9-DEV/Dockerfile.development) and then rebuilding the image.

EDIT: the 2nd CMD stanza will skip the tests.

**Comment by jakob-beetz** [comment]
Great! Thanks, this did the trick for me. 

Adding the ` -DskipTests` switch to the original CMD of the [Dockerfile.development](Dockerfile.development) line 21 skipped the test like you suggested. From my understanding the second one would be a debug build (?). 

Both headless `curl` and web browser on :3000 now work for me. 

Greatly appreciate your responsiveness and support!

**Comment by justin2004** [comment]
great!

> From my understanding the second one would be a debug build (?).

basically. those are the flags i use when i want to build images quickly and do development.

**Comment by luigi-asprino** [comment]
I think we can close this issue (I've successfully built docker container).
