### ISSUE TITLE
Use of fx:cardinal function when also using fx:properties fx:use-rdfs-member true

### ISSUE THREAD

**Issue by laurentlefort** [SPARQL-Anything/sparql.anything#377]
#272  is a good response to cases where the sequencing order the data is received in must be preserved, which is a relatively frequent requirement with XML, CSV or Excel inputs in my projects.

In such cases, I'm interested in also using the fx:use-rdfs-member option as a mean to make the code and output easier to read and the subsequent queries simpler to develop and maintain.

My query looks like this 
construct {
  ?s ?p ?o .
  ?o xyz:cardinal ?cardinal .
} where {
  SERVICE \<x-sparql-anything:media-type=application/json\> {
    fx:properties fx:location ?_file.
    fx:properties fx:use-rdfs-member true.
    ?s ?p ?o .
    BIND(fx:cardinal(?p) AS ?cardinal) 
  }
}

I'm not getting the `?o xyz:cardinal ?cardinal`  triples when running it - I tried the same approach on both JSON and Excel formats. 
But I'm getting them when I comment out the option:  `# fx:properties fx:use-rdfs-member true.`

Can I ask if the fx:cardinal() function is disabled by default when using `fx:properties fx:use-rdfs-member true`?
Would it be possible to change this behaviour, maybe using the same option if there is no significant performance change or a different option otherwise?

**Comment by enridaga** [comment]
Hi, thanks for the questions, interesting case I haven't thought of before.

To answer your question, the `fx:use-rdfs-member` property changes all the `rdf:_1`,`rdf:_1`,`rdf:_n` properties into `rdfs:member`. Therefore, what will be passed to `fx:cardinal` will not be an RDF container membership property, resulting in the `?cardinal` variable being unbound.

To solve your problem, you can change your query into something like this (not tested!):

```
construct {
?s ?p ?o .
?s ?member ?o .
?o xyz:cardinal ?cardinal .
} where {
SERVICE <x-sparql-anything:media-type=application/json> {
fx:properties fx:location ?_file.
?s ?p ?o .
  OPTIONAL { 
    FILTER( STRSTARTS (STR(?p), STR(rdf:_) ) ) .
    BIND(fx:cardinal(?p) AS ?cardinal) .
    BIND(rdfs:member AS ?member )
  }
 }
}
```

**Comment by luigi-asprino** [comment]
Hi, 

thanks for using SPARQL Anything and discussing this problem.
Well, `fx:cardinal(?p)` is a function that takes as input a container membership properties and returns an integer.
When `use-rdfs-member` is set as true, you don't have container membership properties anymore and ?p will be bound to `rdfs:member`, `rdf:type` or `xyz:**local_field**`.
Please note that when using this option, the information about the order of the slots is lost in the triplification.
Hence, it seems to me that `fx:cardinal()` (or any other function) does not have any hint for returning the cardinal number of the slot.

Maybe, a solution could be reifying the statements.
For example, suppose you have the JSON array [1,2,3]. You'll get something like this

```
_:root a fx:root ; rdfs:member 1; rdfs:member 2; rdfs:member 3 .
```

By reifying slots you could also have something like this:

```
<<_:root rdfs:member 1>> fx:slot-key 1 .
<<_:root rdfs:member 2>> fx:slot-key 2 .
<<_:root rdfs:member 3>> fx:slot-key 3 .
```

I used RDF-star notation.

**Comment by luigi-asprino** [comment]
[8cde200](https://github.com/SPARQL-Anything/sparql.anything/commit/8cde200c9aebb2c719918b1354da5d1f9663dc11) introduces the `reify-slot-statements` option (not the best name ever - suggestions welcome) which keeps the slot integer key as an annotation of the triple (see the example [here](https://github.com/SPARQL-Anything/sparql.anything/blob/v0.9-DEV/Configuration.md#reify-slot-statements))

**Comment by luigi-asprino** [comment]
Of course, one needs SPARQL-star for querying the result. Jena supports RDF and SPARQL -star by default.
In SPARQL-star the query looks like the following one

```
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX  xyz:  <http://sparql.xyz/facade-x/data/>
PREFIX  fx:   <http://sparql.xyz/facade-x/ns/>
PREFIX  rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

SELECT ?o ?key
WHERE
  { SERVICE <x-sparql-anything:>
      { fx:properties
                  fx:use-rdfs-member    true ;
                  fx:content            "[3,7,42]" ;
                  fx:reify-slot-statements  true ;
                  fx:media-type         "application/json" .
        ?s        rdfs:member                   ?o  .
        BIND(TRIPLE(?s, rdfs:member, ?o) AS ?t)
        ?t <http://sparql.xyz/facade-x/ns/slot-key> ?key

      }
  }
```

Which yields

|o|key|
|-|-|
|7|2|
|42|3|
|3|1|

**Comment by laurentlefort** [comment]
Thanks for your responses. 
I liked the first one by @enridaga and modified it a bit for my convenience (see below): this gives me a single solution which can be applied to CSV, EXCEL, XML, YAML and JSON inputs.

These changes were motivated by two factors: 
- When the output is formatted as nested blank nodes rather than a list of standalone \_:b0 ...  \_:bb blank nodes . I can "see" its structure and this makes it easier to work out how to process it further.
- For XML content, I felt it is more convenient to have a different property for content that I would get in XSLT by locally calling the text() function. This solution also works OK but only when I also use the headers=true option in CSV or EXCEL. 

It's interesting to see I (eventually) did not need the OPTIONAL { }.

```construct {
?s ?q ?o .
?r xyz:cardinal ?cardinal .
} where {
SERVICE <x-sparql-anything:media-type=application/json> {
fx:properties fx:location ?_file.
?s ?p ?o .
    BIND(fx:cardinal(?p) AS ?cardinal) .
    BIND(IF(STRSTARTS (STR(?p), STR(rdf:_) && ISBLANK(?o), xyz:member, 
                IF(STRSTARTS (STR(?p), STR(rdf:_) && ISBLANK(?o), xyz:text, ?p)) AS ?q)
    BIND(IF(STRSTARTS (STR(?p), STR(rdf:_) && ISBLANK(?o), ?o, 
                IF(STRSTARTS (STR(?p), STR(rdf:_) && ISBLANK(?o), 1/0, 1/0)) AS ?r)
 }
}

**Comment by laurentlefort** [comment]
I think the new option proposed by @luigi-asprino may be useful for cases where the intermediate data produced is an array of strings, decimals or integers in it but I don't have any such a case to volunteer. 
- If this is the case, should the name of the option property be something like add-array-key-to-triple? 
- Should you create a new issue for it with the title containing the information that this is primarily applicable to "arrays"? 
- Can you also share more information on the list of input formats the option is valid for or not (or maybe even use the option name itself to make this applicability info more explicit like you do with some of the other options)?

I also had to read the Jena [RDF-Star documentation](https://jena.apache.org/documentation/rdf-star/) to understand what @luigi-asprino proposed. In my own words, `<<?s ?p ?o>> fx:slot-key ?key` content is created when the data is read and then we can get a quoted triple handle ?t for it and then we can get the ?key value from the `?t fx:slot-key ?key` BGP.

Finally,  have you tried yet to mirror my CONSTRUCT query example to generate the RDF* content? I'm curious to see how legible the result would it be.

**Comment by luigi-asprino** [comment]
> I think the new option proposed by @luigi-asprino may be useful for cases where the intermediate data produced is an array of strings, decimals or integers in it but I don't have any such a case to volunteer.

Not just arrays of primitive types, but also arrays of objects (see the example below).

> If this is the case, should the name of the option property be something like add-array-key-to-triple?

What about `annotate-triple-with-slot-key`?

> Should you create a new issue for it with the title containing the information that this is primarily applicable to "arrays"?

Yes, even if the documentation points to this issue which describes the use-case. But, maybe better opening a new issue for that.

> Can you also share more information on the list of input formats the option is valid for or not (or maybe even use the option name itself to make this applicability info more explicit like you do with some of the other options)?

This is valid for any format using container membership properties to represent list-like information in RDF. This applies to every format.

> I also had to read the Jena [RDF-Star documentation](https://jena.apache.org/documentation/rdf-star/) to understand what @luigi-asprino proposed. In my own words, <<?s ?p ?o>> fx:slot-key ?key content is created when the data is read and then we can get a quoted triple handle ?t for it and then we can get the ?key value from the ?t fx:slot-key ?key BGP.

Exactly.

> Finally, have you tried yet to mirror my CONSTRUCT query example to generate the RDF* content? I'm curious to see how legible the result would it be.

I slightly revised the query 

```
PREFIX ex: <http://example.org/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX fx: <http://sparql.xyz/facade-x/ns/>
PREFIX xyz: <http://sparql.xyz/facade-x/data/>
construct {
  ?slot_iri ex:myNumber ?number ;
    ex:cardinal ?cardinal .
} where {
  SERVICE <x-sparql-anything:media-type=application/json> {
    fx:properties fx:content "[{\"number\": 6},{\"number\": 9},{\"number\": 22}]".
    fx:properties fx:use-rdfs-member true.
    fx:properties fx:reify-slot-statements  true .
    ?s rdfs:member ?o .
    ?o xyz:number ?number .
    << ?s rdfs:member ?o >> fx:slot-key ?cardinal .
    BIND(fx:entity(ex:, ?cardinal) AS ?slot_iri)

  }
}
```

which yields

```
<http://example.org/2> <http://example.org/cardinal> "2"^^<http://www.w3.org/2001/XMLSchema#integer> .
<http://example.org/2> <http://example.org/myNumber> "9"^^<http://www.w3.org/2001/XMLSchema#int> .
<http://example.org/1> <http://example.org/cardinal> "1"^^<http://www.w3.org/2001/XMLSchema#integer> .
<http://example.org/1> <http://example.org/myNumber> "6"^^<http://www.w3.org/2001/XMLSchema#int> .
<http://example.org/3> <http://example.org/cardinal> "3"^^<http://www.w3.org/2001/XMLSchema#integer> .
<http://example.org/3> <http://example.org/myNumber> "22"^^<http://www.w3.org/2001/XMLSchema#int> .
```

**Comment by luigi-asprino** [comment]
By the way, maybe it is also worth adding a function ``isContainerMembershipProperty(?p)`` to avoid ``STRSTARTS (STR(?p), STR(rdf:_) )``

**Comment by luigi-asprino** [comment]
As #378 and #377 are completed I think we can close this issue
