### ISSUE TITLE
Namespace

### ISSUE THREAD

**Issue by luigi-asprino** [SPARQL-Anything/sparql.anything#381]
If we want to control the namespace of containers, properties, classes and graphs as suggested in #19, we need to first reconcile  `root` and `namespace` options.
I can only see one solution for this if it is not explicitly set `root` must be equal to `namespace`

**Comment by enridaga** [comment]
> If we want to control the namespace of containers, properties, classes and graphs as suggested in #19, we need to first reconcile `root` and `namespace` options. I can only see one solution for this if it is not explicitly set `root` must be equal to `namespace`

I am missing why we need to reconcile `root` and `namespace`? 

The `root` should reflect where the resource/datasource is while `namespace` is about prefixing the projected slots. One problem with defaulting `root` to namespace is that the user may lose track of what is the source file the content is about. Having it pointing to he path is a good feature, IMO. (Again, I may have missed the original motivating argument)

**Comment by luigi-asprino** [comment]
Maybe I gave too little context.
The root is a container, therefore, if we want to control the namespace of all the containers with an option, the root must be also considered.
Suppose set `containers-namespace` as `container:`, this would affect all the containers except the root one which will have the location as namespace.

**Comment by luigi-asprino** [comment]
Maybe you are right. Let's first introduce the containers-namespace option and then discuss strategies to reconcile it with the root. I was misled by the fact that the property is called "namespace" but it just applies to properties while other namespaces cannot be controlled.

**Comment by luigi-asprino** [comment]
So I close the issue
