### ISSUE TITLE
The Any23 project is being retired

### ISSUE THREAD

**Issue by enridaga** [SPARQL-Anything/sparql.anything#392]
We have a dependency on Any23 in the HTML module. 

https://attic.apache.org/projects/any23.html

However, this does not mean we need to rush on removing/replacing the dependency, just that we should keep an eye on that because degradation may require that at some point we do it.

**Comment by luigi-asprino** [comment]
I haven't found a good alternative to Any23.
@danbri, can we ask for your help? Maybe, you know some good Java microdata extractors?
Thanks!

**Comment by danbri** [comment]
Take a look inside any23, perhaps you could extract just the bits you need.
Or just use the last stable release and watch out for security issues?

**Comment by luigi-asprino** [comment]
This is an idea, however, Any23 is a quite big project and the bits are not exactly a bit.
Let's see if we can identify what we need.

**Comment by luigi-asprino** [comment]
[8695e6e](https://github.com/SPARQL-Anything/sparql.anything/commit/8695e6e5aababb54d7b66f31f12ddb871fbca818) mirrors part of Any23 library into sparql-anything-html package.
semargl library was mirrored as well as it is used by Any23 for extracting RDFa triples
