### ISSUE TITLE
Apache Jena 5

### ISSUE THREAD

**Issue by enridaga** [SPARQL-Anything/sparql.anything#393]
New release of a cornerstone project for us. Notable changes include new implementations for in-memory graphs, which are *very* relevant to us.

Summary of changes: https://lists.apache.org/thread/vhn0olwcmv755np52qqddn74d5hrnot8

All issues on this release: https://github.com/apache/jena/issues?q=is%3Aissue+closed%3A2023-04-23..2023-07-05

**Comment by luigi-asprino** [comment]
Jena 5 is out. It is time to update the dependency and test it.

**Comment by luigi-asprino** [comment]
[9dffb88](https://github.com/SPARQL-Anything/sparql.anything/commit/9dffb887ab30ddd8dab73ef7554659b7ba1749da) upgrades jena to 5.1.0.
Please note that Jena 5 requires Java 17+, so I've disabled workflows that compiled the project with Java 11 and Java 14.

**Comment by justin2004** [comment]
nice, @luigi-asprino !

should we cut a minor release with jena 5?

**Comment by enridaga** [comment]
[like]  Enrico.Daga reacted to your message:
________________________________
