### ISSUE TITLE
Support for Q-gram distance

### ISSUE THREAD

**Issue by EmidioStani** [SPARQL-Anything/sparql.anything#394]
Hello,

it would be interesting for me to support Q-gram distance.

By looking at the code I see you support those distances from [Apache  Commons](https://commons.apache.org/proper/commons-text/apidocs/org/apache/commons/text/similarity/package-summary.html).

I noticed that the [java-string-similarity](https://github.com/tdebatty/java-string-similarity) supports such distance (and others), released under MIT license and provided through Maven. 

Would it be possible to include it ?

Thanks,

Emidio

**Comment by enridaga** [comment]
Hi Emilio, sure, it makes a lot of sense a nice extension to the function list. 

The process should be easy as adding the dependency and wiring the function using the reflection library we developed. This can be done in different ways, see https://github.com/SPARQL-Anything/sparql.anything/blob/7a48cad1f81c8bea8bf2b7288920d403a37c8ef5/sparql-anything-engine/src/main/java/io/github/sparqlanything/engine/FacadeX.java#L116

**Comment by luigi-asprino** [comment]
[2c5d286](https://github.com/SPARQL-Anything/sparql.anything/commit/2c5d2866073c899803962bb6017a73baf49194ed) introduces the function fx:QGramDistance(?n1, ?n2) for computing the QGram Distance between two strings.

The implementation of the algorithm is provided by the [java-string-similarity](https://github.com/tdebatty/java-string-similarity) library (I couldn't find the implementation on the apache commons).

[579aef7](https://github.com/SPARQL-Anything/sparql.anything/commit/579aef74235c871c5aaf032a3551ee30f5cc1ebe) adds the documentation of the fx:QGramDistance
