### ISSUE TITLE
fuseki failure

### ISSUE THREAD

**Issue by justin2004** [SPARQL-Anything/sparql.anything#396]
after i build using `mvn clean install` then run `java -cp sparql-anything-fuseki/target/sparql-anything-fuseki-0.9.0-SNAPSHOT.jar io.github.sparqlanything.fuseki.Endpoint`

i get
```
Error: Unable to initialize main class io.github.sparqlanything.fuseki.Endpoint
Caused by: java.lang.NoClassDefFoundError: org/apache/commons/cli/ParseException
```

**Comment by justin2004** [comment]
oh this might be related to `-Dgenerate-server-jar`

**Comment by enridaga** [comment]
That is the module jar, not the server. 
Also, you're right, after #376 you need to activate a profile to build the server jar `-Dgenerate-server-jar=true`
