### ISSUE TITLE
[Documentation] Corrupted facade-x-ER.jpg

### ISSUE THREAD

**Issue by enridaga** [SPARQL-Anything/sparql.anything#399]
The file is corrupted, see also https://github.com/SPARQL-Anything/sparql.anything/blob/v0.9-DEV/Facade-X.md

**Comment by luigi-asprino** [comment]
This is driving me crazy.
There is some configuration on my laptop that corrupts the image files.
I've tried to upload a new version of the image via the web interface, but it is still corrupted.
@enridaga, could you please upload the image (for sure it is on overleaf, we used it for the TOIT paper).

**Comment by enridaga** [comment]
The png seems to work, though, maybe we just replace it with that and remove the jpg
