### ISSUE TITLE
Test failure, docker run

### ISSUE THREAD

**Issue by MathiasVDA** [SPARQL-Anything/sparql.anything#402]
Hello,

Following these instruction: https://github.com/SPARQL-Anything/sparql.anything/blob/v0.9-DEV/BROWSER.md#headless-browser

I receive the following test failure:

```
sparql-anything  | [main] ERROR org.apache.jena.riot - There was a problem encountered loading a remote context [code=LOADING_REMOTE_CONTEXT_FAILED].
sparql-anything  | [main] ERROR io.github.sparqlanything.cli.SPARQLAnything - An error occurred while loading /app/sparql-anything-cli/target/test-classes/load-subdirs/dir1/dir2/file
sparql-anything  | [main] ERROR io.github.sparqlanything.cli.SPARQLAnything -  - Problem was: There was a problem encountered loading a remote context [code=LOADING_REMOTE_CONTEXT_FA
sparql-anything  | [main] ERROR org.apache.jena.riot - There was a problem encountered loading a remote context [code=LOADING_REMOTE_CONTEXT_FAILED].
sparql-anything  | [main] ERROR io.github.sparqlanything.cli.SPARQLAnything - An error occurred while loading /app/sparql-anything-cli/target/test-classes/load-subdirs/dir1/file2.jso
sparql-anything  | [main] ERROR io.github.sparqlanything.cli.SPARQLAnything -  - Problem was: There was a problem encountered loading a remote context [code=LOADING_REMOTE_CONTEXT_FA
sparql-anything  | [main] INFO io.github.sparqlanything.cli.SPARQLAnything - Loaded 9 triples
sparql-anything  | Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.888 sec <<< FAILURE!
s
```

**Comment by enridaga** [comment]
Hi, can't reproduce. Was it an effect of the proxy settings and why you made the pull requests https://github.com/SPARQL-Anything/sparql.anything/pull/401 ?

**Comment by MathiasVDA** [comment]
Hello, no this shouldn't have anything to do with proxy issues. The path /app/sparql-anything-cli/target/test-classes/load-subdirs/dir1/dir2/file is local.

Besides, I've also tried this when I'm not on my coorporate network, so then there is no proxy

**Comment by enridaga** [comment]
The failure seems to relate to the JSON-LD parser attempting to load a remote context (and failing)

I can see this json-ld file in my test folder

`sparql-anything-cli/target/test-classes/load-subdirs/dir1/dir2/file3.jsonld11`

the context the message is referring to is remote:
```json
{
      "@context": "https://schema.org",
      "@type": "Person",
      "address": {
...
```

I can't see `sparql-anything-cli/target/test-classes/load-subdirs/dir1/dir2/file` (I guess the terminal output was cropped...).

**Comment by luigi-asprino** [comment]
Does the problem persist? 
I've used the docker container for #450 and it worked.

**Comment by MathiasVDA** [comment]
I can confirm it works for me as well. As topic starter, I'll close this issue but feel free to reopen if that was not appropriate
