### ISSUE TITLE
Jena optimiser not operating within service clauses

### ISSUE THREAD

**Issue by enridaga** [SPARQL-Anything/sparql.anything#424]
See this comment when discussing #330.

              By the way, if the operations within the service are not optimised maybe the execution is not optimal.. maybe we could consider invoking the optimiser in  FXOpExecutor.execute(OpService).

_Originally posted by @luigi-asprino in https://github.com/SPARQL-Anything/sparql.anything/issues/330#issuecomment-1808245604_

**Comment by luigi-asprino** [comment]
[cc850c9](https://github.com/SPARQL-Anything/sparql.anything/commit/cc850c9a3d9ab740da4f0956ee25ba00ce581c96) introduces the optimisation of the service sub-operation before its execution.
Not sure whether this leads to an improvement in performance. 
I think we can close this issue for now.
