### ISSUE TITLE
Making fx and xyz namespace URL return something

### ISSUE THREAD

**Issue by EmidioStani** [SPARQL-Anything/sparql.anything#428]
Hello,

currently in Sparql-Anything there are 2 namespaces associated, both of them can also be found on prefix.cc:

- fx: https://sparql.xyz/facade-x/ns/
- xyz: http://sparql.xyz/facade-x/data/

while the first is associated the functions and magic properties, the 2nd is used to extract data from different data sources.

The fx URL has a link to a index.ttl that is almost empty. The fx URL  could redirect to: https://github.com/SPARQL-Anything/sparql.anything#functions-and-magic-properties

like sparql-generate does for http://w3id.org/sparql-generate/fn/

Unfortunately jena does point to file not found for (afn) https://jena.apache.org/ARQ/function and Ontotext redirects to the home page for (ofn)  http://www.ontotext.com/sparql/functions/

The xyz URL returns a page 404 on GitHub. It could contain text saying that is a space reserved for associating properties extracted.

Best,

Emidio

**Comment by enridaga** [comment]
This should be solved now.
