### ISSUE TITLE
How to get comments from DOCX?

### ISSUE THREAD

**Issue by luigi-asprino** [SPARQL-Anything/sparql.anything#443]
### Discussed in https://github.com/SPARQL-Anything/sparql.anything/discussions/430

<div type='discussions-op-text'>

<sup>Originally posted by **kvistgaard** November 18, 2023</sup>
From what I tried so far, it seems they are not accessible.
Yet, since they are what I mostly need to get from MS Word documents, I'm hoping that there is a way (I saw such an option for spreadsheets) or that it can be implemented.</div>

**Comment by kvistgaard** [comment]
@luigi-asprino , any updates on that?

**Comment by luigi-asprino** [comment]
[7912bb9](https://github.com/SPARQL-Anything/sparql.anything/commit/7912bb94b642c5319deee4ee8064c3ed07d4a277) implements the extension to extract comment documents.
Comments are interpreted as containers with three slots containing the id, the author and the text of the comment. Comment Containers are attached to the paragraph the comment refers to.

See [this docx](https://github.com/SPARQL-Anything/sparql.anything/blob/v1.0-DEV/sparql-anything-docs/src/test/resources/Doc4.docx) and [its RDF counterpart](https://github.com/SPARQL-Anything/sparql.anything/blob/v1.0-DEV/sparql-anything-docs/src/test/resources/Doc4.ttl)

**Comment by kvistgaard** [comment]
@luigi-asprino excellent, I'll give it a try very soon. At a first glance it's not obvious how a comment is linked to what it is a comment on, and the thread: commentY isResponseTo comment commentX

**Comment by kvistgaard** [comment]
> [7912bb9](https://github.com/SPARQL-Anything/sparql.anything/commit/7912bb94b642c5319deee4ee8064c3ed07d4a277) implements the extension to extract comment documents.

Now I see that it's for 1.0. I've been trying with the latest release 0.9.0. When will it be released?

**Comment by luigi-asprino** [comment]
You can try it out with the pre-release v1.0-DEV.4 that has just been created. 

https://github.com/SPARQL-Anything/sparql.anything/releases/tag/v1.0-DEV.4

**Comment by kvistgaard** [comment]
Thanks. Just tested it. Works great. Excellent work.
Do you have any thoughts on the [threads](https://github.com/SPARQL-Anything/sparql.anything/issues/443#issuecomment-2269270628)?

**Comment by luigi-asprino** [comment]
I am reopening it to try to make the comments thread clearer.

**Comment by luigi-asprino** [comment]
At the moment, comments in the same thread are attached as subsequent slots of the container for the paragraph.

Suppose you have a paragraph "Paragraph1" with two comments ("This is a comment" and "This is a reply").

This results into two slots 2 and 3 referencing the comments

```
<http://www.example.org/document/paragraph/2>
        rdf:type  xyz:Paragraph;
        rdf:_1    "Paragraph1";
        rdf:_2    <http://www.example.org/document/Comment_0>;
        rdf:_3    <http://www.example.org/document/Comment_1> .

<http://www.example.org/document/Comment_1>
        rdf:type  xyz:Comment;
        rdf:_1    <http://www.example.org/document/Comment_1/Author>;
        rdf:_2    <http://www.example.org/document/Comment_1/CommentText>;
        rdf:_3    <http://www.example.org/document/Comment_1/CommentId>.

<http://www.example.org/document/Comment_1/CommentId>
        rdf:type  xyz:CommentId;
        rdf:_1    "1" .

<http://www.example.org/document/Comment_1/CommentText>
        rdf:type  xyz:CommentText;
        rdf:_1    "This is a reply" .

<http://www.example.org/document/Comment_1/Author>
        rdf:type  xyz:CommentAuthor;
        rdf:_1    "Luigi Asprino" .


<http://www.example.org/document/Comment_0>
        rdf:type  xyz:Comment;
        rdf:_1    <http://www.example.org/document/Comment_0/Author>;
        rdf:_2    <http://www.example.org/document/Comment_0/CommentText>;
        rdf:_3    <http://www.example.org/document/Comment_0/CommentId>.


<http://www.example.org/document/Comment_0/CommentId>
        rdf:type  xyz:CommentId;
        rdf:_1    "0" .

<http://www.example.org/document/Comment_0/CommentText>
        rdf:type  xyz:CommentText;
        rdf:_1    "This is a comment" .

<http://www.example.org/document/Comment_0/Author>
        rdf:type  xyz:CommentAuthor;
        rdf:_1    "Luigi Asprino" .

```

A possible solution would be adding the thread comment number as a slot of the comment.

```
<http://www.example.org/document/Comment_1>
        rdf:type  xyz:Comment;
        rdf:_1    <http://www.example.org/document/Comment_1/Author>;
        rdf:_2    <http://www.example.org/document/Comment_1/CommentText>;
        rdf:_3    <http://www.example.org/document/Comment_1/CommentId>;
        rdf:_4    <http://www.example.org/document/Comment_1/ThreadCommentNumber> .

<http://www.example.org/document/Comment_1/ThreadCommentNumber>
        rdf:type  xyz:ThreadCommentNumber;
        rdf:_1    "2"^^xsd:int .

<http://www.example.org/document/Comment_0>
        rdf:type  xyz:Comment;
        rdf:_1    <http://www.example.org/document/Comment_0/Author>;
        rdf:_2    <http://www.example.org/document/Comment_0/CommentText>;
        rdf:_3    <http://www.example.org/document/Comment_0/CommentId>;
        rdf:_4    <http://www.example.org/document/Comment_0/ThreadCommentNumber> .

<http://www.example.org/document/Comment_0/ThreadCommentNumber>
        rdf:type  xyz:ThreadCommentNumber;
        rdf:_1    "1"^^xsd:int .

**Comment by kvistgaard** [comment]
I was imagining something more in the style of [sioc:has_reply](https://www.w3.org/submissions/sioc-spec/#term_has_reply) + sioc:Thread but I guess what you suggest would work equally well.

**Comment by luigi-asprino** [comment]
The relationship between comments and their replies is implicit in the order of the comments. Therefore, sioc:has_reply + sioc:Thread can be materialised with a SPARQL construct if necessary. This is in line with the SPARQL Anything philosophy of using the minimum number of operations to transform data into RDF and leaving the transformation to the user.

**Comment by kvistgaard** [comment]
@luigi-asprino Currently, there is a document part (paragraph, heading) on which the comment is made that is nicely linked with the comment. Is there a way to extract also the highlighted part of the text of that item on which the comment is made?
