### ISSUE TITLE
Generate format page automatically

### ISSUE THREAD

**Issue by luigi-asprino** [SPARQL-Anything/sparql.anything#444]
I'm tired of updating format description pages manually at every update. 
Why not generate them automatically?
We can maybe add some annotations to triplifiers containing the description of the triplifier together with other information that can be found on the format page.
Then, by using a script we can populate a template for the format page.

**Comment by enridaga** [comment]
It's a great idea to start working with annotations. Apart from documentation, we could use annotations to plug triplifiers, using reflection to find implementations for a given format/mime-type. We would then be able to remove that nasty dependency between engine and all the triplifiers modules. 

Maybe we could open a discussion and define an annotation schema for triplifiers?

About documentation, one thing II find annoying is the duplication between GH documentation and deployable docs on readthedocs. We should probably make the README slimmer, including stuff such as how to contribute, and only pointing to the documentation directly in the `docs` folder (and/or on readthedocs.io).

**Comment by luigi-asprino** [comment]
> It's a great idea to start working with annotations. Apart from documentation, we could use annotations to plug triplifiers, using reflection to find implementations for a given format/mime-type. We would then be able to remove that nasty dependency between engine and all the triplifiers modules.

This is great! I'm not familiar with such mechanisms, but happy to contribute if you see some benefit!

> Maybe we could open a discussion and define an annotation schema for triplifiers?

Maybe we can focus the issue on the objective, e.g. What's the annotation schema for removing dependencies?

> About documentation, one thing II find annoying is the duplication between GH documentation and deployable docs on readthedocs. We should probably make the README slimmer, including stuff such as how to contribute, and only pointing to the documentation directly in the `docs` folder (and/or on readthedocs.io).

I must admit I didn't check the readthedocs version frequently.
Isn't it generated from the markdown files, I mean it is true that there is a duplication, but it is for free thanks to the settings that you developed.

**Comment by luigi-asprino** [comment]
The annotations needed to automatically generate the markdown page documenting a supported format are the following:

- **Package-level annotation** to be added to the package containing the triplifiers for the format. The package annotations have to specify the _name_ of the format (e.g. "Slides"), a _description_ describing how the format is interpreted via the Facade-X  metamodel, and a _resource_ to use as an example. The binary flag indicates that the format targets binary files. 
```java
@Format(
		name = "Slides",
		description = "A slide is a single page of a presentation....",
		resourceExample = "https://sparql-anything.cc/examples/Presentation3.pptx",
               binary = true
)
package io.github.sparqlanything.slides;

import io.github.sparqlanything.model.annotations.Format;

```

- **Class-level annotation**. Triplifier annotation has to be added to the Triplifier class.
```java

package io.github.sparqlanything.slides;

import io.github.sparqlanything.model.*;
import io.github.sparqlanything.model.annotations.Example;
import io.github.sparqlanything.model.annotations.Option;
import org.apache.commons.compress.utils.Sets;
import org.apache.poi.xslf.usermodel.*;
import org.apache.xmlbeans.XmlObject;
import org.openxmlformats.schemas.presentationml.x2006.main.CTExtensionList;
import org.openxmlformats.schemas.presentationml.x2006.main.CTPresentation;

import javax.xml.namespace.QName;
import java.io.IOException;
import java.io.InputStream;
import java.net.URL;
import java.util.*;
import java.util.concurrent.atomic.AtomicInteger;

@io.github.sparqlanything.model.annotations.Triplifier
public class PptxTriplifier implements Triplifier {
..
}
```

- **Field-level annotation** to indicate the options available for the format. The tag option allows to indicate theg description and the valid values of the option (name and default value are retrieved from the IRIArgument object). Example tag allows us to provide example of usage of the option. It requires a resource to triplify, a query, and possibly, a description of the example. **Note**: multiple Examples can be added to a field.
```java
@io.github.sparqlanything.model.annotations.Triplifier
public class PptxTriplifier implements Triplifier {

	@Example(resource = "https://sparql-anything.cc/examples/Presentation2.pptx", query = "CONSTRUCT { ?s ?p ?o . } WHERE { SERVICE <x-sparql-anything:location=https://sparql-anything.cc/examples/Presentation2.pptx,slides.extract-sections=true> { ?s ?p ?o } }")
	@Option(description = "It tells the document triplifier to extract the sections of the presentation (see #435)", validValues = "true/false")
	public static final IRIArgument EXTRACT_SECTIONS = new IRIArgument("slides.extract-sections", "false");

```

The class DocumentationGenerator within the module `sparql-anything-documentation-generator` is responsible for scanning the project and generating the documentation.

**Comment by luigi-asprino** [comment]
The documentation generator module has been created, the modules have been annotated and the documentation generated.
The documentation is generated with the script `update-docs.sh` (which compiles the project and executes the DocumentationGenerator class).
I think this can be closed now.

**Comment by luigi-asprino** [comment]
I reopen it as I get an exception when the resource example is provided inline in the query.
