### ISSUE TITLE
Rename bib module as bibliograpghy

### ISSUE THREAD

**Issue by luigi-asprino** [SPARQL-Anything/sparql.anything#445]
I think it is more meaningful

**Comment by enridaga** [comment]
There are still a few references to `sparql-anything-bib` around (see #447): 

https://github.com/search?q=repo%3ASPARQL-Anything%2Fsparql.anything%20sparql-anything-bib&type=code

**Comment by luigi-asprino** [comment]
This can be closed as #447, #449 and #450 are addressed
