### ISSUE TITLE
CodeQL action fails

### ISSUE THREAD

**Issue by enridaga** [SPARQL-Anything/sparql.anything#447]
Strange behaviour, the error seems due to a maven build failing to find `sparql-anything-bib:1.0.0-SNAPSHOT`:

https://github.com/SPARQL-Anything/sparql.anything/actions/runs/7397409737/job/20124470191#step:4:3421

**Comment by enridaga** [comment]
Ah! It was renamed to `sparql-anything-bibliography` recently

**Comment by enridaga** [comment]
Reopened #445

**Comment by luigi-asprino** [comment]
> Ah! It was renamed to `sparql-anything-bibliography` recently

Oops I didn't know that affects codeql workflow..

**Comment by luigi-asprino** [comment]
My bad! In the engine module the dependency was not updated with the new `artifactId`.
Hope this fix the issue

**Comment by luigi-asprino** [comment]
How can we trigger the workflow?

**Comment by luigi-asprino** [comment]
It works now https://github.com/SPARQL-Anything/sparql.anything/actions/runs/7448788548/job/20263911494
I've also added a status badge to the README
