### ISSUE TITLE
How to capture piece of XML to a literal as is?

### ISSUE THREAD

**Issue by VladimirAlexiev** [SPARQL-Anything/sparql.anything#452]
https://github.com/semantalytics/xsparql/issues/38

I have an XML file with stuff like this:
```xml
      <plu:geometry>
        <gml:Polygon srsName="http://www.opengis.net/def/crs/EPSG/0/25833" srsDimension="2">
          <gml:exterior>
            <gml:LinearRing>
              <gml:posList>385919.31860777 5824690.697477636 ...</gml:posList>
            </gml:LinearRing>
          </gml:exterior>
        </gml:Polygon>
      </plu:geometry>
```
and I want to capture it as a GeoSPARQL literal like this:
```sparql
construct {...  ?geo a geo:Geometry; geo:asGML ?gmlLiteral}
where {... bind(fx:literal(?geometry,geo:gmlLiteral) as ?gmlLiteral).
```

But a trivial script:
```sparql
prefix fx:   <http://sparql.xyz/facade-x/ns/>
construct {
  ?s ?p ?o
} where {
  SERVICE <x-sparql-anything:media-type=application/xml> {
    fx:properties fx:location ?_file.
    fx:properties fx:use-rdfs-member true.
    ?s ?p ?o
  }
}
```
already breaks up every XML structure into triples, eg
```ttl
rdfs:member  [ rdf:type     <http://inspire.ec.europa.eu/schemas/plu/4.0#geometry> ;
               rdfs:member  [ rdf:type          <http://www.opengis.net/gml/3.2#Polygon> ;
                              rdfs:member       [ rdf:type     <http://www.opengis.net/gml/3.2#exterior> ;
                                                  rdfs:member  [ rdf:type     <http://www.opengis.net/gml/3.2#LinearRing> ;
                                                                 rdfs:member  [ rdf:type     <http://www.opengis.net/gml/3.2#posList> ;
                                                                                rdfs:member  "385541.00331503904 5824758.839786618 ..."]]] ;
                              xyz:srsDimension  "2" ;
                              xyz:srsName       "http://www.opengis.net/def/crs/EPSG/0/25833"]] ;
```
I'd rather not have to re-serialize the above RDF into XML.

So is it possible to tell it "give me a certain XML element as text", rather than converting it to triples?
(I mean the complete XML structure with sub-elements, not just its text content)

**Comment by enridaga** [comment]
> I mean the complete XML structure with sub-elements, not just its text content

Interesting use case, unfortunately, this can't be done with the XML triplifier. Maybe you can try to pretend it's HTML, I think that triplifier should have an `innerHTML` property that in principle should return the GML code. See [the documentation](https://sparql-anything.readthedocs.io/en/latest/formats/HTML/) for details and let us know if it solves your problem.

**Comment by VladimirAlexiev** [comment]
@enridaga It kind of works, but not quite. See test files at https://gist.github.com/VladimirAlexiev/318ab4924c756ead618ebdded6428509 and compare
- sparql-anything-test-xml.ttl
- sparql-anything-test-html.ttl

I use these prefixes:
```sparql
prefix x:     <http://www.w3.org/1999/xhtml#>              # raw data prefix in HTML->RDF, prepended to any other prefix, eg x:gml:featurecollection, x:plu:indicationreference, x:nilreason, x:xsi:nil
prefix html:  <https://html.spec.whatwg.org/#>             # html:innerHTML, html:innerText
prefix xlink: <http://www.w3.org/1999/xlink#>
prefix gml:   <http://www.opengis.net/gml/3.2#>
prefix plu:   <http://inspire.ec.europa.eu/schemas/plu/4.0#>
prefix xyz:   <http://sparql.xyz/facade-x/data/>           # raw prefix in XML->RDF data
prefix fx:    <http://sparql.xyz/facade-x/ns/>             # fx:properties in SERVICE call, fx:root in output
prefix rdf:   <http://www.w3.org/1999/02/22-rdf-syntax-ns#># each XML element becomes rdf:type
prefix rdfs:  <http://www.w3.org/2000/01/rdf-schema#>      # rdfs:member
prefix xsd:   <http://www.w3.org/2001/XMLSchema#>
prefix xsi:   <http://www.w3.org/2001/XMLSchema-instance#> # xsi:nil "true": filter out such elements. xsi:schemaLocation
```
Problems:
- all elements are lowercased: both inside innerHTML and in RDF
- all elements in RDF are prepended the `x:` prefix, eg `x:gml:featurecollection, x:plu:indicationreference, x:xsi:nil`
(the originals are gml:FeatureCollection, plu:indicationReference, xsi:nil`

I guess I can live with this, but the script will be completely non-portable between XML and HTML input...

**Comment by enridaga** [comment]
> I guess I can live with this, but the script will be completely non-portable between XML and HTML input...

Of course, this is a hack, XML is different from HTML.

We can open issues to support the case better, when using the HTML triplifier with XML content. To summarise, these seems to be the problems:

- xmlns is not considered a ns prefix, and the default whatwg namespace is prepended (#468)
- element names are lowercased, while in XML tags are case sensitive (#466)

**Comment by VladimirAlexiev** [comment]
@enridaga Yes!

Note: It's not the `whatwg` namespace, but the `xhtml` namespace. 
Actually I've renamed them in my script, see the comments below as to where they appear:
```sparql
prefix x:     <http://www.w3.org/1999/xhtml#>              # raw data prefix in HTML->RDF, prepended to any other prefix, eg x:gml:featurecollection, x:plu:indicationreference, x:nilreason, x:xsi:nil
prefix html:  <https://html.spec.whatwg.org/#>             # html:innerHTML, html:innerText
```

**Comment by enridaga** [comment]
> @enridaga Yes!
> 
> Note: It's not the `whatwg` namespace, but the `xhtml` namespace. Actually I've renamed them in my script, see the comments below as to where they appear:
> 
> ```sparql
> prefix x:     <http://www.w3.org/1999/xhtml#>              # raw data prefix in HTML->RDF, prepended to any other prefix, eg x:gml:featurecollection, x:plu:indicationreference, x:nilreason, x:xsi:nil
> prefix html:  <https://html.spec.whatwg.org/#>             # html:innerHTML, html:innerText
> ```

My suspicion is that this depends on the fact that the HTML parser (from jsoup) does not handle prefixes. Will investigate.

**Comment by enridaga** [comment]
JSoup also has an XML parser. We shall allow users to use that instead of the default HTML parser

**Comment by enridaga** [comment]
I also created #468 to implement namespace resolution for both xhtml and xml sources with the HTML triplifier

**Comment by enridaga** [comment]
About case sensitivity, the XML parser (after #466) now generates case-sensitive entity names, included as-is for `innerHTML`.

**Comment by enridaga** [comment]
@VladimirAlexiev I've added a test to show the current behaviour (using your example): 

https://github.com/SPARQL-Anything/sparql.anything/blob/v1.0-DEV/sparql-anything-html/src/test/resources/XML.xml

https://github.com/SPARQL-Anything/sparql.anything/blob/v1.0-DEV/sparql-anything-html/src/test/resources/XML.ttl

**Comment by VladimirAlexiev** [comment]
Yes! This is what I need
https://github.com/SPARQL-Anything/sparql.anything/blob/cbabcd5aea3dadac176299750c5593d3ac0ac76e/sparql-anything-html/src/test/resources/XML.ttl#L81

**Comment by enridaga** [comment]
We can close this one
