### ISSUE TITLE
Querying a specific Excel file's sheet from the BGP 

### ISSUE THREAD

**Issue by AchilleSalaun** [SPARQL-Anything/sparql.anything#478]
Hello,

I try to query a specific sheet in an Excel file. This file is stored locally, and its path contains white spaces.

The following query (see [#22](https://github.com/SPARQL-Anything/sparql.anything/issues/22)) works but doesn't take in consideration the sheets (all the triples from both sheets are mixed):

```
PREFIX fx:  <http://sparql.xyz/facade-x/ns/>

SELECT ?s ?p ?o
WHERE {
    SERVICE <x-sparql-anything:> {
        fx:properties fx:location "/some path with white spaces/Book1.xlsx";
                      fx:spreadsheet.headers true.       
    
        ?s ?p ?o .
    }
}
```

Conversely, the following query (see [#351](https://github.com/SPARQL-Anything/sparql.anything/issues/351)) selects the triples from a specific sheet (`target_sheet`), as long as the path to the file doesn't contain any white space:

```
PREFIX fx:  <http://sparql.xyz/facade-x/ns/>

SELECT ?s ?p ?o
WHERE {
    SERVICE <x-sparql-anything:file://path_without_white_spaces/Book1.xlsx> {
        fx:properties fx:spreadsheet.headers true.       
    
        GRAPH <file://path_without_white_spaces/Book1.xlsx#target_sheet> {
            ?s ?p ?o .
        }
    }
}
```
 
My attempts combining these queries have been unsuccessful.
Is there any way to have both? As in querying a specific sheet from a file stored locally, whose path contains white spaces?

Ideally, I was expecting the following query to work:

```
PREFIX fx:  <http://sparql.xyz/facade-x/ns/>

SELECT ?s ?p ?o
WHERE {
    SERVICE <x-sparql-anything:> {
        fx:properties fx:location "/some path with white spaces/Book1.xlsx#target_sheet";
                      fx:spreadsheet.headers true.       
    
        ?s ?p ?o.
    }
}
```

Sorry by advance if I missed any obvious solution.

**Comment by luigi-asprino** [comment]
Hi,

White spaces are automatically replaced with their percent-encoding representation i.e. "%20"
Therefore, I expect the following query to work.

[Edit: I corrected the query]

```
PREFIX fx:  <http://sparql.xyz/facade-x/ns/>

SELECT ?s ?p ?o
WHERE {
    SERVICE <x-sparql-anything:> {
        fx:properties fx:location "/some path with white spaces/Book1.xlsx";
                 GRAPH </some%20path%20with%20white%20spaces/Book1.xlsx#target_sheet> {
                      fx:spreadsheet.headers true.       
    
        ?s ?p ?o.
    }
}
```

I've done some experiments in [1989dc1](https://github.com/SPARQL-Anything/sparql.anything/commit/1989dc1bea1041153f3ffd04dc15d0f65ed9b811)

**Comment by AchilleSalaun** [comment]
Hi Luigi,

It makes perfect sense and works great: this was the example I was looking for.
Thank you very much for your prompt reply!
