### ISSUE TITLE
Broken workflow badges on stable documentation (after upgrades jena to 5.1.0)

### ISSUE THREAD

**Issue by enridaga** [SPARQL-Anything/sparql.anything#492]
[9dffb88](https://github.com/SPARQL-Anything/sparql.anything/commit/9dffb887ab30ddd8dab73ef7554659b7ba1749da) upgrades jena to 5.1.0.
Please note that Jena 5 requires Java 17+, so I've disabled workflows that compiled the project with Java 11 and Java 14.

_Originally posted by @luigi-asprino in https://github.com/SPARQL-Anything/sparql.anything/issues/393#issuecomment-2254165857_
            
As an effect of removing the workflows, the documentation badges are broken

<img width="757" alt="Screenshot 2024-08-20 at 18 00 51" src="https://github.com/user-attachments/assets/f0953b9e-de65-48ee-81cd-7b9e37503ce0">

Apparently, there is no way of generating badges per branch, but branches are specified on a url parameter -- basically workflows need to exist on the default branch! We can restore the workflow and disable them on the v1.0 branch

**Comment by luigi-asprino** [comment]
I've restored workflows for Java 11 and 14 on default branch.
They are now triggered on pushes of branch v0.9-DEV
I see the badges on the [stable documentation](https://sparql-anything.readthedocs.io/stable/), so I suppose this fix the issue.

**Comment by luigi-asprino** [comment]
I think we can close this issue now since the badge works fine.
