### ISSUE TITLE
Default CLI output for SELECT queries is CSV (not TEXT as the CLI help says)

### ISSUE THREAD

**Issue by luigi-asprino** [SPARQL-Anything/sparql.anything#507]
Either we fix the documentation, which says TEXT, or the code.
CSV is more machine-readable and TEXT is more human-readable, what do you think is more comfortable?

**Comment by luigi-asprino** [comment]
Let's stick with CSV and change the documentation only

**Comment by enridaga** [comment]
I think we wrote TEXT because:

- SELECT -> CSV (text/csv)
- ASK -> true/false
- CONSTRUCT / DESCRIBE -> Turtle (text/turtle)

But there is no harm in being more specific in the help text.

**Comment by luigi-asprino** [comment]
[28d6d1a](https://github.com/SPARQL-Anything/sparql.anything/commit/28d6d1a1cf6fcb8bb62a04dd625f2725c7d8e84e) corrects the CLI help and the README
