### ISSUE TITLE
Support CSV first row as header

### ISSUE THREAD

**Issue by alexdma** [SPARQL-Anything/sparql.anything#51]
If my CSV has a first row as header, as in the example:
<pre>email,id,first name,last name<br/>laura@example.com,2070,Laura,Grey<br/>craig@example.com,4081,Craig,Johnson<br/>mary@example.com,9346,Mary,Jenkins<br/>jamie@example.com,5079,Jamie,Smith<br/></pre>
could I supply an option for the headers to provide additional property bindings (escaping spaces and all) instead of `rdf:_x`?

Based on the code at [CSVTriplifier.java](https://github.com/SPARQL-Anything/sparql.anything/blob/c64d581d4e73afbed7515f4b8aa58e496a8ce3cf/sparql.anything.csv/src/main/java/com/github/spiceh2020/sparql/anything/csv/CSVTriplifier.java), I tried to pass `-Dcsv.headers=true`, but it doesn't seem to be picked up by the way the engine passes Java properties to the triplifier.

**Comment by enridaga** [comment]
Passing x-sparql-anything protocol options via -D java properties is not supported.
Two ways to do that:

- within the x-sparql-anything uri, e.g.: `x-sparql-anything:location=...,csv.headers=true`
- using magic properties, since #35  (however this is a new feature and it is not documented yet

**Comment by alexdma** [comment]
Thanks, hadn't realised that was the way to pass properties too.

Can the convention for encoding whitespaces in headers be customised? By default, if I scan for properties on the above example (with a `SELECT ?property`), the result set shows bad URIs like

    <http://sparql.xyz/facade-x/data/last name>
    
 which I cannot seem to be able to use in actual queries:
* `<http://sparql.xyz/facade-x/data/last name>` results as expected in a parsing error
* `<http://sparql.xyz/facade-x/data/last+name>` is not bound
* `<http://sparql.xyz/facade-x/data/last%20name>` is not bound either

**Comment by enridaga** [comment]
Good catch! Exploring the characters to encode in URL paths, which are different from the ones in the query part. This may be useful: https://stackoverflow.com/a/2849800/1035608

**Comment by enridaga** [comment]
7c3829383807b59d5f8539028bb510d4402c283b should provide a fix. Does it solve the problem?

Another related issue is that probably we should format local names in the builder class and have a unified strategy but this requires some more thought, probably.

**Comment by alexdma** [comment]
Yes, URLencoding works just fine, both in the example and the data I'm working with.
