### ISSUE TITLE
Load JAR files dynamically at Runtime

### ISSUE THREAD

**Issue by luigi-asprino** [SPARQL-Anything/sparql.anything#513]
This could be useful for adding custom triplifiers or functions without having to recompile the whole project.

I found this

https://stackoverflow.com/questions/60764/how-to-load-jar-files-dynamically-at-runtime

If there aren't better solutions, we could add a CLI option for passing the filepaths to the jars to be loaded.

**Comment by enridaga** [comment]
This is also related to the problem with packing a very large executable jar, even if not all the features are always needed. This was discussed in #484 but we didn't come out with a plan yet.

**Comment by luigi-asprino** [comment]
We could add an option to the CLI for passing as the path to a JAR file to make CLI include the package dynamically. 

This would allow the development of additional features (triplifiers, functions or magic properties) in separate JARs.

As for #484, we can remove the features that require heavy dependencies and distribute them as separate JARs as well. We can also have a build with all the features for those who don't have limited resources.

**Comment by luigi-asprino** [comment]
The CLI and the server now have the option `-j <filepath>` that allows us to pass a filepath of an executable JAR that will be dynamically loaded.
JAR must implement the interface PluginInitializer as described [here](https://github.com/SPARQL-Anything/sparql.anything/blob/v1.0-DEV/EXTENSION_MECHANISMS.md) that will register the extensions (i.e. triplifiers, functions or magic properties) implemented in the JAR.

**Comment by luigi-asprino** [comment]
We can close the issue now
