### ISSUE TITLE
ClassNotFoundException for Triplifiers

### ISSUE THREAD

**Issue by sebastianthelen** [SPARQL-Anything/sparql.anything#514]
I use SPARQL Anything to consume data from an XML source. The latest releases seem to have problems with different data sources and cause ClassNotFoundExceptions for specific triplifiers. In my case `java.lang.ClassNotFoundException: io.github.sparqlanything.xml.XMLTriplifier.`

I can't share my query to reproduce the exact same problem because my endpoints are internal. A similar issue can be reproduced using the query from the documentation, i.e., 
```
PREFIX xyz: <http://sparql.xyz/facade-x/data/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX fx: <http://sparql.xyz/facade-x/ns/>

SELECT ?seriesName
WHERE {

    SERVICE <x-sparql-anything:https://sparql-anything.cc/example1.json> {
        ?tvSeries xyz:name ?seriesName .
        ?tvSeries xyz:stars ?star .
        ?star fx:anySlot "Courteney Cox" .
    }

}
```
which results in `java.lang.ClassNotFoundException: io.github.sparqlanything.json.JSONTriplifier`.

The problem seems so have emerged with v1.0-DEV.5 and higher.  v1.0-DEV.4 is not affected by this issue. I'm running the server version of Sparql Anything (sparql-anything-server-v1.0-DEV.X.jar) and execute the queries from the UI.

**Comment by luigi-asprino** [comment]
Hi,

the problem was introduced in the #484 in which we introduced the libs module to collect all the triplifiers and remove them from the engine model.
The dependencies of the fuseki module need to be updated.

**Comment by luigi-asprino** [comment]
It works now. https://github.com/SPARQL-Anything/sparql.anything/releases/tag/v1.0-DEV.8 fixes the problem
