### ISSUE TITLE
discussion: more facades for less work

### ISSUE THREAD

**Issue by justin2004** [SPARQL-Anything/sparql.anything#53]
instead of implementing (from scratch) facades for different file types from i was wondering if it might be helpful to make use of visidata's loaders. visidata has a [couple dozen](https://www.visidata.org/formats/) implemented already in what they call [loaders](https://github.com/saulpw/visidata/tree/stable/visidata/loaders).

[visidata](https://www.visidata.org/) treats all data as sheets (so it might be similar to the list of lists approach this project is taking).

and thanks for putting this idea out there and making this project. i really like the idea of handling the re-engineering problem automatically.

**Comment by enridaga** [comment]
Thank you for the pointer, that's a brilliant project and you're right, the philosophy is pretty much the same! 
I see the project is in python, though, not sure how efficiently to reuse it from our Java codebase.
Surely an example for us!

**Comment by enridaga** [comment]
I think we can settle this as we can now use external commands as input to our facade. Assuming a tool like the ones mentioned above can be used as command lines, SPARQL Anything can read the STDIN and operate on the content _as-if_ it was in one of the supported formats, JSON or CSV, for example.
