### ISSUE TITLE
Consistent way to generate URIs

### ISSUE THREAD

**Issue by enridaga** [SPARQL-Anything/sparql.anything#56]
Currently, facade keys are passed by triplifiers assuming that they are well-formed local names (slash or hash). We should centralise the preprocessing of keys in the facadeXbuilder (and make ourself clear about what type of preprocessing is needed)

**Comment by enridaga** [comment]
This is partly addressed within #91

**Comment by enridaga** [comment]
However, rationale should be documented

**Comment by luigi-asprino** [comment]
This is addressed by #380

**Comment by luigi-asprino** [comment]
Documentation can be found here https://github.com/SPARQL-Anything/sparql.anything/blob/v0.9-DEV/Facade-X.md
