### ISSUE TITLE
API pagination with parameter bindings as range of integers

### ISSUE THREAD

**Issue by enridaga** [SPARQL-Anything/sparql.anything#61]
One useful thing is to generate API calls dynamically to paginate remote resources. A possible solution is to support a special syntax for inline param values (see #55), for example: `-v page=1...10` could be equivalent to: `-v page=1 -v page=2 -v page=3 ... -v page=10`

**Comment by enridaga** [comment]
I am not 100% sure this is a neat way of doing it, so I leave this issue open for discussion.

**Comment by justin2004** [comment]
@enridaga  speaking of API pagination, what about API HTTP headers? 

e.g.
```
curl -X GET \
  'https://test.com/search?name=fred' \
  -H 'authorization: Token <your_token>'
```

is there anywhere to add the authorization header in sparql anything?

**Comment by justin2004** [comment]
turns out the answer is no.
but i see where to add it so i am working on it.

hopefully it will be a welcome addition to sparql anything.

**Comment by enridaga** [comment]
> @enridaga speaking of API pagination, what about API HTTP headers?
> 
> e.g.
> 
> ```
> curl -X GET \
>   'https://test.com/search?name=fred' \
>   -H 'authorization: Token <your_token>' \
>   -H 'someotherheader: blahblah123'
> ```
> 
> is there anywhere to add authorization and someotherheader in sparql anything?

This is now possible with #67

**Comment by enridaga** [comment]
I would say this issue can be closed.
