### ISSUE TITLE
http redirects

### ISSUE THREAD

**Issue by justin2004** [SPARQL-Anything/sparql.anything#65]
programmatically downloading this public google sheet involves an http redirect.

```
curl --location 'https://docs.google.com/spreadsheets/d/1RlmIKTdWtctk4rszSqFRuYdHeSeGTYTWiwyrmOH_RCA/export?exportFormat=csv'
```

if you follow the redirection it looks like the resource is 
```
https://doc-0o-c8-sheets.googleusercontent.com/export/70cmver1f290kjsnpar5ku2h9g/8v0uungb9eioggmq52ukis9ng8/1627131370000/11
4675124106815611566/*/1RlmIKTdWtctk4rszSqFRuYdHeSeGTYTWiwyrmOH_RCA?exportFormat=csv
```
but you need some additional http headers to download it (which the redirection process adds).

now with 
```
...
SERVICE <x-sparql-anything:media-type=text/csv,https://docs.google.com/spreadsheets/d/1RlmIKTdWtctk4rszSqFRuYdHeSeGT
YTWiwyrmOH_RCA/export?exportFormat=csv>
...
```
i think sparql-anything might be corrupting the url:
```
ERROR 2021-07-24 12:53:49,805 [qtp739333799-14] (FacadeXOpExecutor.java:168) - An error occurred
java.io.IOException: Server returned HTTP response code: 400 for URL: https://doc-0o-c8-sheets.googleusercontent.com/export/70cmver1f290kjsnpar5ku2h9g/3j5v9vkineg858jn64lbd5avfs/1627131225000/114675124106815611566/*/1RlmIKTdWtctk4rszSqFRuYdHeSeGTYTWiwyrmOH_RCA?exportFormat
```
see how the `=csv` is missing at the end

**Comment by enridaga** [comment]
There may be a limitation in the way properties are expressed in the service URI (I think escaping the = with \= may work).

However, the following method is more robust and seems to work:
```

```
PREFIX xyz: <http://sparql.xyz/facade-x/data/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX fx: <http://sparql.xyz/facade-x/ns/>

SELECT * 

WHERE {
	SERVICE <x-sparql-anything:> {
	  fx:properties fx:location "https://docs.google.com/spreadsheets/d/1RlmIKTdWtctk4rszSqFRuYdHeSeGTYTWiwyrmOH_RCA/export?exportFormat=csv" ;
	    fx:media-type "text/csv" 
		.
	  ?a ?b ?c
	}
}

**Comment by enridaga** [comment]
BTW, while working on #66 the HTTP Client should also follow redirect by default.

**Comment by justin2004** [comment]
>(I think escaping the = with \= may work).

just wanted to note that i was able to escape an = with two backslashes today.

i got the idea from looking at this line:
https://github.com/SPARQL-Anything/sparql.anything/blob/fc9b4f1e41db4102d38abe7c31ed527ea89d63fd/sparql.anything.parser/src/main/antlr4/FacadeIRI.g4#L74

**Comment by enridaga** [comment]
> just wanted to note that i was able to escape an = with two backslashes today.

Are you sure? In principle, you should only use two if you are into a Java String. To check that, I added one test which reads the string from a file, using a single backslash: 2676a7f6f5a05fbd1766967c0bbaec59122188a3

**Comment by enridaga** [comment]
Anyway, if the problem with the escaping persists, probably better to open another issue. The original problem of this one seems resolved.

**Comment by justin2004** [comment]
>Are you sure? In principle, you should only use two if you are into a Java String. 

ah, yes. you are right. i was evaluating the sparql select from within a bash shell so it was similar to being in a java string.

i agree. this one is fixed.
