### ISSUE TITLE
Functions with container membership properties

### ISSUE THREAD

**Issue by enridaga** [SPARQL-Anything/sparql.anything#78]
Useful functions are:

- previous(rdf:_2) -> rdf:_1
- next(rdf:_2) -> rdf:_3
- before(rdf:_1,rdf:_10) -> true
- after(rdf:_10,rdf:_1) -> true

**Comment by enridaga** [comment]
Others:

- forward(rdf:_2, 3) -> rdf:_5
- backward(rdf:_5, 3) -> rdf:_2

**Comment by justin2004** [comment]
nice.

yeah, you could do math on the slot number but that is tedious:
`bind(xsd:integer(replace(str(?p),str(rdf:_),"")) as ?p_num)`

**Comment by enridaga** [comment]
That's completed. If anybody thinks about another one, they can open a new issue.
