### ISSUE TITLE
Function `serial`

### ISSUE THREAD

**Issue by enridaga** [SPARQL-Anything/sparql.anything#86]
I have a use case in which I need to generate a CSV from data extracted from a number of JSON files. Ideally, the CSV should include a numeric ID. I am not 100% sure but I believe that generating a serial id is not something doable in SPARQL. If this is true, maybe I want SPARQL Anything to have a function such as `fx:serial` that generates an incremental ID during query execution.

**Comment by justin2004** [comment]
if it doesn't need to be sequential but just unique there is struuid(): https://www.w3.org/TR/sparql11-query/#func-struuid

EDIT: i was comment happy. clearly `serial` means you want this to be sequential.  :S

**Comment by enridaga** [comment]
> EDIT: i was comment happy. clearly serial means you want this to be sequential. :S

That was useful anyway as I double-checked my options in SPARQL and finally used an md5, numeric hash, which is deterministic on a number of key fields. Good enough for now but still I would like to have `serial` at some point.

**Comment by enridaga** [comment]
Implemented `serial(...)` with any number of args. The function sets a counter in the ARQ Context for each argument list. Every time the function is executed, the counter progresses. Multiple counters can be set by passing different arguments. Some examples can be found in the tests. Note that args are kept in memory as keys of a map, which may grow very large if one wants, for example, associate a counter to some value during query execution (useful to spot duplicates without using aggregation). Other use cases are possible, for example, generating entity URIs from combination of values without necessarily putting them in the URI.

**Comment by enridaga** [comment]
It would be nice to do some tests on use cases. If using the arg list as a key for the map is too memory intensive we may replace them with some hash (no need to keep references to the actual objects).

**Comment by enridaga** [comment]
> It would be nice to do some tests on use cases. If using the arg list as a key for the map is too memory intensive we may replace them with some hash (no need to keep references to the actual objects).

Keeping this idea in the background and close this issue. A new one can be opened if the idea is relevant.
