### ISSUE TITLE
BASIL template variables matched in comments

### ISSUE THREAD

**Issue by enridaga** [SPARQL-Anything/sparql.anything#88]
Strings such as `?_location` should be ignored when in comments.

**Comment by enridaga** [comment]
This is very annoying to resolve and not particularly useful either. I am inclined to close with a Won't fix (silly it is, since I opened it myself)

**Comment by justin2004** [comment]
@enridaga 
One thing we could do...

Apache Jena can parse SPARQL ([to pretty print it](https://github.com/justin2004/sparql_pretty/blob/master/Dockerfile#L7)) and when it does it removes comments.
So we could run that on the query then do variable substitution.
