### ISSUE TITLE
question: can you use strategy with fuseki?

### ISSUE THREAD

**Issue by justin2004** [SPARQL-Anything/sparql.anything#90]
can you specify strategy in an fx:property or in the service URI?

```
 -s,--strategy <strategy>              OPTIONAL - Strategy for query
                                       evaluation. Possible values: '1' -
                                       triple filtering (default), '0' -
                                       triplify all data. The system
                                       fallbacks to '0' when the strategy
                                       is not implemented yet for the
                                       given resource type.
```

**Comment by enridaga** [comment]
There is a general point about using numerous CLI options with the Fuseki server. One possibility is to move the implementation details outside the SPARQL Anything CLI class to a more general manager that can be then reused within servlets as well.

**Comment by justin2004** [comment]
@enridaga now you've got me wondering if we can just use the fuseki server for everything you want to do.

as i look at the cli options...
(just thinking out loud)

--format  can be done with      curl -H 'Accept: application/something'

--input    i need to try first to understand what it does

--load    i think the case of a single file and a directory is already handled with a `<x-sparql-anything:location=/some/path>`

--output    just need a shell redirection     curl ... > out.trig

--output-pattern       feels like it can be done with just fueski but it would need some development and it is related to #70 (which i think is interesting). 

--query       all my examples are curl --data-urlencode 'query=some sparql here'   and if there is a file it is just   curl --data @/path/to/some.rq i think

--strategy       this discussion :)

--values     i need to try it but it sounds like a org.apache.jena.query.ParameterizedSparqlString.  this might be nice to do as         fx:properties fx:query.location "/path/some.rq"  and allow that referenced query to use bindings in scope. i actually looked into doing something like this a while back. i actually fetched the file /path/some.rq and i considered replacing the current OpService with the derived OpService from the file  [here](https://github.com/justin2004/sparql.anything/blob/fdf44c95adf79b4078871a51066fc364957025c3/sparql.anything.engine/src/main/java/com/github/spiceh2020/sparql/anything/engine/FacadeXOpExecutor.java#L171-L194)
it works but bindings make it not easy to use. e.g. in the following query the whole service gets replaced by /mnt/some.rq but it has been a few days so i don't remember exactly why it wasn't easy to use.
```
PREFIX xyz: <http://sparql.xyz/facade-x/data/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix fx: <http://sparql.xyz/facade-x/ns/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
select *
WHERE {
        ?s ?p ?o
        service <x-sparql-anything:query.location=/mnt/some.rq>{
        ?s ?pp ?o
        }
}
```

i think my interest in seeing the fuseki server become the first class thing is that that is how deployments are usually done. also the persistence of the server has some benefits... the ability to keep things in memory between queries, the ability to maintain a on-disk TDB (for handling large files), etc.

**Comment by enridaga** [comment]
This is interesting discussion, maybe we should split it in different issues? Some of these can be solved by supporting the options within the service spec (e.g. a `strategy` option can be easily added) but others require a bit more thinking, for example, the way parametrised queries can be implemented by reading from the query string. 

The `--values` option allows for populating variables in the query with data, following [this convention].(https://github.com/basilapi/basil/wiki/SPARQL-variable-name-convention-for-WEB-API-parameters-mapping). This could be implemented as pre-processor, inspecting the query string ([BASIL](https://github.com/basilapi/basil) does that to generate APIs dynamically as stored queries).
The difference with `ParametrizedQueryString` is that the template can specify datatypes, allowing to apply the appropriate transformation from the provided input string (e.g `--values var=1` needs to become `"1"` or the number `1`? ). This is not a problem from Java code but can be complicated if we ask users to provide a serialised literal from the CLI/HTTP call such as `--values var="\"1\"^^xsd:string\"` ... 

The utility of this option in the CLI lies on the fact that we can reuse the same query. If queries are just sent to the Fuseki server every time, it does not seem to make much sense. 
But you were thinking about referencing a query from within a service clause, can you elaborate more on the use case?

The `--input` parameter is supposed to be a SPARQL Result Set, each row is read and values used as-if they were passed via --values (the query is executed many times). I am not sure this is something that is worth replicating on a client/server setting, unless we start considering long-running background jobs (probably premature). 

`--output-pattern` really depends on `--input` as it is a way of customising the output file name on multiple executions.

`--format` should work already as a feature of Fuseki. Not sure that the exact same formats are supported, though.

**Comment by justin2004** [comment]
>But you were thinking about referencing a query from within a service clause, can you elaborate more on the use case?

Yeah, it is just the [named query](https://patterns.dataincubator.org/book/named-query.html) pattern.

[Processor](https://github.com/AtomGraph/Processor) does it with [data](https://github.com/AtomGraph/Processor/blob/83ff768959e6580bdf1d8220b3456bda539483c3/examples/wikidata/wikidata.ttl#L62).

Blazegraph does it like [this](https://github.com/blazegraph/database/wiki/StoredQuery#invoking-a-stored-query).
But with Blazegraph you have to register a query first. I was just exploring what it might look like with SPARQL Anything since it doesn't require you to register files beforehand. 


I didn't know what BASIL was though. I am going to tell my colleagues about BASIL... especially if it can generate Swagger specifications.

Thanks for describing the other CLI options. I'll have to use them some to see if i can get a sense for if I would like to have similar functionality from fuseki.

**Comment by enridaga** [comment]
I like the idea of using SERVICE clauses to glue existing queries altogether. In the case of SELECT queries this is trivial, I am unsure about how to handle CONSTRUCT queries -- I guess we need an additional BGP to be in the enclosing SERVICE clause, otherwise we throw an error. Probably `ASK` and other type of queries should not be allowed.
