### ISSUE TITLE
html triplifier -- slots only connect to their own container

### ISSUE THREAD

**Issue by justin2004** [SPARQL-Anything/sparql.anything#93]
at HEAD i think the html triplifier is broken:

```
service <x-sparql-anything:blank-nodes=true,media-type=text/html,location=https://www.w3.org/TR/sparql11-query>
```

yields:
```
_:b0    a               xhtml:code ;
        rdf:_1          _:b0 ;
        rdf:_2          " | " ;
        rdf:_3          _:b0 ;
        rdf:_4          " | " ;
        rdf:_5          _:b0 ;
        rdf:_6          " | " ;
        rdf:_7          _:b0 ;
```

but at commit 23e8075d50a0da198c3eeba6cd1d80c62f02b8f3 the result looks like:
```
[ a               fx:root , xhtml:html ;
  rdf:_1          [ a               xhtml:head ;
                    rdf:_1          [ a                 xhtml:meta ;

```

**Comment by enridaga** [comment]
Just sketched a temporary test to discuss this (see commit). The test currently uses a `{ ?a ?b ?c }` pattern, which seems to return much more stuff, also considering the default `follow redirect` policy of the HTTP client. However, to reproduce the problem it would be useful to see the entire query. There may be the chance that there is a problem in the TripleFiltering method, which has become the default strategy for the HTML triplifier, or a bug in the HTML triplifier has been introduced while implementing #91.

**Comment by enridaga** [comment]
BTW, to run the test, uncomment the `@Ignore` annotation as tests should not assume online resources ...

**Comment by justin2004** [comment]
oh, the problem isn't the amount that is returned. the problem is that all slots point to the containing container.

```
curl --silent 'http://localhost:3000/sparql.anything' \
--header "Accept: text/csv" \
--data-urlencode 'query=
PREFIX fx: <http://sparql.xyz/facade-x/ns/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX xyz: <http://sparql.xyz/facade-x/data/>
construct {?s ?p ?o}
where {
service <x-sparql-anything:blank-nodes=true,media-type=text/html,location=https://www.geonames.org/postalcode-search.html?q=90210&country=US> {
?s ?p ?o
}
}'
```


yields:
```
_:b9    a       <http://www.w3.org/1999/xhtml#html> , fx:root ;
        rdf:_1  _:b9 ;
        rdf:_2  _:b9 ;
        ...
```

but it should yield something like:
```
[ a               fx:root , xhtml:html ;
  rdf:_1          [ a               xhtml:head ;
                    rdf:_1          [ a                 xhtml:meta ;
                    ...
```

**Comment by justin2004** [comment]
i actually think something like this might make a good test case:

```
curl --silent 'http://localhost:3000/sparql.anything' \
--header "Accept: text/csv" \
--data-urlencode 'query=
PREFIX fx: <http://sparql.xyz/facade-x/ns/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX xyz: <http://sparql.xyz/facade-x/data/>
ask
where {
service <x-sparql-anything:blank-nodes=true,media-type=text/html,location=https://www.geonames.org/postalcode-search.html?q=90210&country=US> {
?root a fx:root .
?higher ?slotp ?root .
}
}'
```

it should always return false because the root node should not be the object of any triple.

**Comment by enridaga** [comment]
> oh, the problem isn't the amount that is returned. the problem is that all slots point to the containing container.

Ah! I get it now, I didn't notice the same bnode repeated in the first example.

**Comment by enridaga** [comment]
Added a test as suggested in https://github.com/SPARQL-Anything/sparql.anything/issues/93#issuecomment-922136822
Test passes, the bug should be resolved.
