### ISSUE TITLE
Jena 4

### ISSUE THREAD

**Issue by enridaga** [SPARQL-Anything/sparql.anything#94]
Is it time to consider moving to Jena 4? 
Major reasons are:

 - support for RDF-Star
 - support for JSON-LD 1.1
 - better support for custom service executor (see also #60)

Besides, they are already at version 4.2.0 so I suppose this is robust enough. Not sure what is the impact on our codebase, though.

**Comment by justin2004** [comment]
wow, it it just worked!?

**Comment by luigi-asprino** [comment]
Well.. there were a couple classes deprecated and few methods added.. but not much work..  
The upgrade passed all the unit tests. The tool seems to be working properly.
